### ISSUE TITLE
[6-2장] 쿼리 실행 절차 중 2단계 "불필요한 조건의 제거 및 복잡한 연산의 단순화"

### ISSUE THREAD

**Issue by yebink** [gazi-gazi/real-mysql#1]
> `p.264` 두 번째 단계는 첫 번째 단계에서 만들어진 SQL 파스 트리를 참조하면서 다음과 같은 내용(아래 4개)을 처리한다.

질문 : 그 중에서 **불필요한 조건의 제거 및 복잡한 연산의 단순화** 가 잘 이해가 안 되는데 예시가 있으면 좋을 것 같아요.

**Comment by yebink** [comment]
![image](https://user-images.githubusercontent.com/19922698/99901656-7ec22c00-2cfb-11eb-8bf3-9791f59313ce.png)
이러한 쿼리에서 서브쿼리를 사용하지만 옵티마이저는 내부적으로 JOIN으로 바꿔서 처리해준다.

이는 `EXPLAIN EXTENDED [실제 쿼리]`키워드를 이용해 내부에서 수행된 쿼리를 볼 수 있다.

```
[2020-11-22 19:43:16] [HY000][1003] 
/* select#1 */ 
select `rms`.`employees`.`emp_no` 
AS `emp_no`,`rms`.`employees`.`birth_date` 
AS `birth_date`,`rms`.`s`.`emp_no` 
AS `emp_no`,`rms`.`s`.`salary` 
AS `salary`,`rms`.`s`.`from_date` 
AS `from_date`,`rms`.`s`.`to_date` 
AS `to_date` from `rms`.`employees`
join `rms`.`salaries` `s` 
where (`rms`.`s`.`emp_no` = `rms`.`employees`.`emp_no`)
```
<br/>

하지만 `EXPLAIN EXTENDED` 요놈은 이제 deprecated된다.
공식문서에 의하면 `MySQL 8.0` 부터는 `EXPLAIN` 이후의 `SHOW WARNINGS`로 위의 정보를 볼 수 있다고 하니 참고하자.

**Comment by begaonnuri** [comment]
자문자답 좋네요 👍

**Comment by pci2676** [comment]
```sql
SELECT *
FROM employee_name
WHERE emp_no = 10001 AND emp_no BETWEEN 10001 AND 10005;
```
아래와 같이 튜닝됨
```sql
select NULL AS `emp_no`,NULL AS `first_name`,NULL AS `last_name` 
from `rms`.`employee_name` 
where multiple equal(10001, NULL)
```
