### ISSUE TITLE
[6-2장] Range checked for each record에서 인덱스 레인지 스캔을 하는 경우

### ISSUE THREAD

**Issue by yebink** [gazi-gazi/real-mysql#10]
> `p.306 ~ 307` 최종적으로 인덱스 레인지 스캔을 사용하는 경우는 언제일까

질문 :
```sql
EXPLAIN
SELECT *
FROM employees e1, employees e2
WHERE e1.emp_no >= 1
AND e2.emp_no >= e1.emp_no;
```

```sql
EXPLAIN
SELECT *
FROM employees e1, employees e2
WHERE e1.emp_no >= 100000000
AND e2.emp_no >= e1.emp_no;
```

책에서 말한대로 e1.emp_no가 1 이상일 때, 1억 이상일 때를 모두 조회해봤는데 둘 다 type이 `ALL`이고 `Range checked for each record (index map: 0x1)`가 출력되는 것을 확인했어.

후자일 때는 ALL이 아니라 range같은 애들이 나와야 할 것 같은데 왜 안 나오지??

**Comment by KimSeongGyu1** [comment]
307p 두번째 문단에 이렇게 써있는데
`쿼리 실행 계획의 type 칼럼의 값이 ALL로 표시되어 풀 테이블 스캔으로 처리된 것으로 해석하기 쉽다. 하지만 Extra 칼럼에 "Range checked for each record"가 표시되면 type 칼럼에는 ALL로 표시된다. 즉 "index map"에 표시된 후보 인덱스를 사용할지 여부를 검토해서 이 후보 인덱스가 별로 도움이 되지 않는다면 최종적으로 풀 테이블 스캔을 사용하기 때문에 ALL로 표시된 것이다`

써져 있는 글을 보면 `Range checked for each record`일 때 무조건 ALL을 표시하는 것이 규칙인 것으로 보이구 왜 그렇게 했는지 뇌피셜을 적어보면
실제 실행해보지 않으면 ALL인지 range인지 알기 힘든 값이므로 실행계획에서는 보수적으로 무조건 ALL로 표시하도록 설정했다고 생각해

**Comment by yebink** [comment]
굿굿 요약하자면 Range checked for each record는 실제로 어떤 스캔을 했냐와 무관하게 항상 ALL이 표시된다는 거구만! 이해했다!

그럼 실제로 어떤 스캔을 했는지 알 수 있는 방법은 없나?

-> 두 개의 실행계획에서 row가 다르다.
