### ISSUE TITLE
[6-2장] Full scan on NULL key 연산의 조건 두 가지

### ISSUE THREAD

**Issue by pci2676** [gazi-gazi/real-mysql#11]
> `p.299` 정의대로 연산을 수행하기 위해 이 조건은 다음과 같이 비교돼야 한다.

질문 : 위 구문 바로 아래 두가지 조건이 있는데 해당 상황에서의 실행결과 보여주면 좋을 듯

**Comment by KimSeongGyu1** [comment]
책에서 NULL에 대한 연산의 규칙이 무엇인지 구체적으로 보여주지 않고 있어서 우선 규칙에 대한 진리 표를 첨부
![image](https://user-images.githubusercontent.com/56247080/100540764-bc3a3280-3282-11eb-967d-635c6c570f81.png)

**Comment by KimSeongGyu1** [comment]
1. 서브 쿼리가 1건이라도 결과 레코드를 가진다면 최종 비교 결과는 NULL
(1) 실행계획에서 null 확인
![image](https://user-images.githubusercontent.com/56247080/100540960-27383900-3284-11eb-8549-042357899fd9.png)
(2) 실제 실행에도 아무것도 조회되지 않는 것 확인
![image](https://user-images.githubusercontent.com/56247080/100540973-33bc9180-3284-11eb-9507-5f9545694d2a.png)

**Comment by KimSeongGyu1** [comment]
1. 서브 쿼리가 결과 레코드를 가지는 경우 null 확인
![image](https://user-images.githubusercontent.com/56247080/100541307-6c5d6a80-3286-11eb-94cd-02c17a23185c.png)


2. 서브 쿼리가 1건도 결과 레코드를 가지지 않는 경우 0(false)를 확인
![image](https://user-images.githubusercontent.com/56247080/100541295-45069d80-3286-11eb-96be-d65f56948974.png)
