### ISSUE TITLE
[6-2장] 커버링 인덱스

### ISSUE THREAD

**Issue by pci2676** [gazi-gazi/real-mysql#14]
> `p.313 ~ 315`

질문 : 커버링 인덱스는 성능향상을 위해서 엄청 중요하다고 보는데 이 부분에 대해서 조건같은것들 정리해 두면 좋을것 같아

**Comment by begaonnuri** [comment]
## 커버링 인덱스

### 사용하면 좋은 이유
데이터(테이블 스캔)를 하나도 안읽고 인덱스만 읽어서 처리할 수 있어. 그래서 성능이 빠른거지.

### 사용 조건

#### 1. 클러스터링 인덱스인 경우

먼저 클러스터링 인덱스는 PK값이 비슷한 레코드끼리 묶어서 저장하는거야. 
클러스터링 인덱스의 경우 리프노드에 데이터가 있기 때문에 클러스터링 인덱스의 경우 보조 인덱스에 PK값을 저장하도록 해.
따라서 클러스터링 인덱스에서 커버링 인덱스 조건은 인덱스 컬럼, PK만을 사용하는 쿼리인 경우를 말해.
책의 예를 같이 보면,

```sql
SELECT first_name FROM employees WHERE first_name BETWEEN 'Babette' AND 'Gad';
```

WHERE 조건에서 first_name만을 비교하고있지? 이 경우 컬럼이 인덱싱이 되어있는 상태라서 빠르게 처리가 가능해.
하지만 다음의 경우를 보면,

```sql
SELECT first_name , birth_date -- birth_date 추가
FROM employees WHERE first_name BETWEEN 'Babette' AND 'Gad';
```

SELECT절에 birth_date가 추가됐어. 결과로 가져와야 될 값이 하나 추가된거야.
하지만 first_name만 인덱스가 걸려있어서 먼저 first_name으로 값을 찾고, 그 값에 해당하는 birth_date를 테이블 스캔으로 가져와야돼.
그렇기 때문에 성능이 느린거야. 인덱스만으론 처리가 안되는거지.


추가로 다음 예도 보면,

```sql
SELECT first_name , emp_no -- emp_no 추가
FROM employees WHERE first_name BETWEEN 'Babette' AND 'Gad';
```

이번엔 birth_date 말고 emp_no가 추가됐어.
위에서 클러스터링 인덱스는 보조 인덱스로 PK를 갖는다고 했잖아? 그래서 이 경우도 인덱스만으로 처리가 가능해.
클러스터링 인덱스는 `설정한 인덱스 + PK`라고 생각하면 돼.

#### 2. 논클러스터링 인덱스인 경우 

논클러스터링 인덱스인 경우엔 보조 인덱스로 PK가 아닌 레코드가 저장된 주소값을 가져.
그렇기 때문에 1번의 마지막 예를 다시 보면,

```sql
SELECT first_name , emp_no -- emp_no 추가
FROM employees WHERE first_name BETWEEN 'Babette' AND 'Gad';
```

emp_no라는 PK를 인덱스에서 갖고 있지 않기 때문에 논클러스터링 인덱스의 경우 위 쿼리문의 성능이 느려.
논클러스터링 인덱스는 `설정한 인덱스 + 레코드 주소`라고 생각하면 돼.

**Comment by jjj0611** [comment]
https://12bme.tistory.com/149
