### ISSUE TITLE
[6-3장] max_seeks_for_key는 언제 사용될까

### ISSUE THREAD

**Issue by yebink** [gazi-gazi/real-mysql#19]
> `p.330` 풀 테이블 스캔의 조건 중 마지막 친구

질문 : max_seeks_for_key가 무엇인지, 어떤 경우에 사용하는건지 (사실 사용할 일이 있는지) 궁금해요.

**Comment by toneyparky** [comment]
우선 말씀해주신 마지막 친구가 왜 나왔는지를 생각해보아요.

`6.3.1`절은 풀 테이블 스캔에 대해서 설명하는 절이죠. 이는 인덱스를 사용하지 않는 작업이구요. 
앞선 세개의 친구는 풀 테이블 스캔에 대해서 설명하는 친구들이에요. 그런데 마지막 친구는 `반대로`라는 말로 시작하죠. 즉 저 값을 설정하면 MySQL 서버가 풀 테이블 스캔이 아니라 인덱스 스캔을 사용하도록 유도할 수 있다는 의미에요. 

---

마지막 친구가 왜 나왔는지를 알아봤으니 이제 예빈케이가 궁금해하는 `max_seeks_for_key`가 무엇인지 조금 더 살펴보죠.

>max_seeks_for_key
키를 기반으로 열을 찾을 때 검색 (seek)하는 최대 추정 숫자의 한계. MySQL 옵티마이저는, 인덱스를 스캐닝해서 테이블에서 매칭 열을 찾을 때, 인덱스의 실제 기수 (cardinality)에는 상관 없이 키 검사의 숫자가 이것보다 크지 않다고 가정한다. 이것을 작은 값으로 설정해서(100 정도) MySQL로 하여금 테이블 스캔 대신에 인덱스 스캔 하도록 만들 수가 있다. [출처](http://www.dbguide.net/db.db?cmd=view&boardUid=146579&boardConfigUid=9&boardIdx=127&boardStep=1)

어렵죠? 정리하자면 이 값이 낮을 수록 MySQL 서버가 인덱스 스캔을 사용할 가능성이 높아지는거에요.
그렇다면 여기서 드는 궁금증! 
이 값의 기본값은 얼마일까요?

![image](https://user-images.githubusercontent.com/37579660/100975541-88605500-3581-11eb-996d-e8cbe6cb0b2f.png)
[출처 : MySQL 8.0 공식 문서(우리 책 버전과 다름 주의)](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html)

64bit 기준으로 `18446744073709551615`네요.
WOW😃

이는 아래 사진과 같이 unsigned int64의 최댓값이에요
![image](https://user-images.githubusercontent.com/37579660/100975702-c78ea600-3581-11eb-8fcd-ff99b3a7bb2b.png)
즉 엄청 크게(거의 최대로) 기본값 설정을 해뒀다라고 이해가 됩니다.

그러기에 이를 낮춰서 활용하라는 의미겠지요.

---

이렇게 `max_seeks_for_key`에 대해 알아봤어요. 그러면 어떤 경우에 사용되는지, 혹은 실제 사용되는지에 대해서 알아보죠. 
이 질문에 대한 정확한 답변은 찾지 못했어요. 하지만 해당 키워드에 대해서 자세하게 설명해둔 [링크](https://major.io/2007/08/03/obscure-mysql-variable-explained-max_seeks_for_key/)를 찾았습니다.
조금 오래된 글이지만 (2007) 내용이 좋네요.

링크를 발번역하자면 `MySQL` 공식문서에 풀 테이블 스캔을 피하기 위해 `max_seeks_for_key=1000` 옵션을 주라는 예시가 나옵니다. 여기서부터 링크의 설명이 시작되네요. 그리고 공식문서는 위의 옵션이 `옵티마이저에게 1000개 이상의 키를 찾는 키스캔은 없다고 가정`하는거라고 하네요. 
이 가정에 대해서 조금 더 알아보죠. 최대치가 설정이 되어있다면 옵티마이저는 테이블 안의 인덱스를 스캐닝하며 알맞는 로우를 찾을 때에 최대치보다 많은 수의 키를 찾을 필요가 없다고 가정해요. 인덱스의 실제 카디널리티에 상관 없이요. 
여기서 카디널리티를 한 번 더 알아보죠. 인덱스의 유니크한 값들의 숫자의 예상치라고 하네요. 카디널리티가 높을 수록 MySQL이 조인을 할 때 인덱스를 사용할 가능성이 올라간다고 합니다. 
이제 기본지식이 쌓였으니 본격적인 내용을 더 알아봅시다. 카디널리티는 인덱스에 있는 얼마나 많은 아이템들이 유니크한지를 나타냅니다. 즉 인덱스된 컬럼에 10개의 값들이 있고 같은 두개의 값들이 전체적으로 재사용 된다고 가정해보죠. 그러면 카디널리티는 낮을거에요. (1과 2라는 두개의 값이 총 합쳐서 10번 사용되는 경우) 반면 PK를 인덱스 된 컬럼의 값으로 사용된다면 카디널리티가 높겠죠. 이 경우에는 모든 각 행이 유니크하니까요. 
그렇다면 이게 `max_seeks_for_key`와 무슨 상관이 있을까요? 핵심은 아시다시피 이거죠. 이 값이 낮을 수록 MySQL 서버는 인덱스 스캔을 사용한다(카디널리티가 낮더라도 -> 인덱스 스캔이 비효율적이라고 예측되더라도). 인덱스 스캔을 사용하면 쿼리를 처리하는 데 걸리는 시간을 줄여주게 되죠. 그렇다면 왜 MySQL은 `max_seeks_for_key`의 기본 값을 낮춰서 인덱스 스캔을 사용하도록 유도하지 않는걸까요?
**이 값을 1000으로 낮춘다면 MySQL에게 인덱스의 카디널리티가 1000이 넘더라도 인덱스를 사용할 것이라고 말하는 거에요.** 그리고 저는 이 값을 1로 해도 몇 몇 서버에서는 문제가 없는걸 봤습니다. 
저도 왜 이 값의 기본값이 이렇게 높은지 모르겠네요. 알면 알려주세요~
번역 끝

처음에는 괜찮은 내용의 링크다 싶었는데 뒤로 갈수록 핵심은 안나오네요....😂

무튼 제 예상은 MySQL 옵티마이저가 보기에 해당 쿼리의 카디널리티가 낮아서 인덱스 스캔을 사용하는 것이 비효율적이라고 예측되는 쿼리가 있다고 해봐요. 이 쿼리는 풀 테이블 스캔을 사용하도록 유도 되겠죠. 이 상황에서 `max_seeks_for_key`의 값을 낮게 설정하므로서 인덱스 스캔을 강제하는 방식을 적용하기 위해 사용된다고 생각됩니다.

이상하거나 궁금한 점은 댓글~ 갠톡~ 회식~ 모두 가능~

**Comment by yebink** [comment]
우와 자세한 답변 감사합니다 토니 😉

> 이 값을 1000으로 낮춘다면 MySQL에게 인덱스의 카디널리티가 1000이 넘더라도 인덱스를 사용할 것이라고 말하는 거에요.

이 부분이 좀 모호해요! 그럼 카디널리티 정보는 옵티마이저가 쿼리 실행을 인덱스 스캔으로 할지 풀 스캔으로 할지 결정할 때 필요한 변수인건가요?

<br/>

그리고 토니가 찾아준 `unsigned long long` 값! mysql에서는 `BIGINT`라고 부르는데, mysql에서 취급할 수 있는 가장 높은 숫자라고 하네요. [참고](https://dev.mysql.com/doc/refman/8.0/en/integer-types.html)
숫자를 1만 높여서 `SET max_seeks_for_key=18446744073709551616;`으로 설정하면 에러가 나요.

왜 가장 높은 숫자를 설정해두었는지는 저도 모르겠습니다!

**Comment by jjj0611** [comment]
max_seeks_for_key라는 변수는 key를 최대 몇 건만 읽으면 된다고 판단하게 만들어주는 변수지? 즉 이걸 1000으로 설정한다는 것은 어떠한 key 스캔도 1000건 이상 안 발생할거야! 라고 알려주는 변수인거지. 그럼 이게 제일 높은 값이라고 생각해봐. 풀 테이블 스캔을 하는 상황 중 하나는 옵티마이저가 읽어야할 로우가 많다고 판단하는 경우라고 했잖아. 이 값이 높으면 그만큼 키가 있을 수 있기 때문에 풀 테이블 스캔으로 넘어가지. 근데 이 값을 낮게 설정하면 이걸 속일 수 있겠지. 야 이거 키 스캔하면 아무리 많아도 100건 밖에 안나와! 그러면 스캔 건수가 작기 때문에 풀 테이블 스캔을 하지 않고 인덱스 스캔을 하게 되겠지. 나는 이걸 낮게 설정하는게 그런 의미라고 생각해. 그래서 토니가 번역한 거에서 1이어도 문제가 없는 서버를 봤다고 하는데 만약 옵티마이저가 풀 테이블 스캔을 하는 기준이 1001건이라면 사실 이 값이 1000이든 1이든 항상 인덱스를 사용하기 때문에 크게 의미가 없지 않을까? 하는 생각이야~1001건이 넘어야 풀테이블을 할텐데 1000건 미만이면 어짜피 그냥 인덱스를 사용하게 되는거지.

이 값이 무작정 높은 이유는 옵티마이저가 풀 테이블 스캔을 할 로우의 임계점을 나름 잘 잡았기 때문 아닐까? 그래서 그냥 그걸 옵티마이저에게 기본적으로 맡기게 되는거지(얼마 이상이면 니가 알아서 풀 테이블 스캔으로 바꿔!) 근데 이 변수를 변경해서 우리가 의도한대로 동작하도록 만드는 것 아닐까?

**Comment by jjj0611** [comment]
`p.218`에서 보면 인덱스를 통해 레코드 1건을 읽는 것이 테이블에서 직접 레코드 1건을 읽는 것보다 4~5배 정도 더 비용이 많이 드는 작업인 것으로 예측하기 때문에 읽어야할 레코드 건수가 전체 테이블 레코드의 20~25% 이상이면 직접 읽는 것이 더 효율적이라고 했어.

그렇기 때문에 저 값이 높았던 것이 아닐까 싶어. 만약 max_seeks_for_key라는 변수를 1000으로 놓는다면, 40000건인 테이블에서 10000건의 로우를 읽어야 할 때 풀 테이블 스캔을 해야할텐데, 옵티마이저에게 key 스캔이 1000건을 넘지 않을거야! 라고 말하므로써 "어 그럼 인덱스로 읽어도 되겠다"라고 생각을 하면서 인덱스로 읽도록 만드는거라고 좀 더 정리가 된 것 같아. 저 변수 때문에 아무리 많아도 key를 1000건이상 읽을거라고 생각하지 않는거지(실제로는 10000건이 필요한데!)

그리고 이걸 optimizer가 잘 계산하기 때문에 이 값을 최대로 놨을거라고 좀더 강한 믿음이 생겼어! 그렇지만 그럼에도 너네가 index로 읽어야될 필요가 있으면 이 값을 바꿔! 라고 해놓은거지.
