### ISSUE TITLE
[6-2장] select_type 중 UNCACHEABLE UNION

### ISSUE THREAD

**Issue by begaonnuri** [gazi-gazi/real-mysql#2]
> `p.277` 소제목 UNCACHEABLE UNION

질문 : 책에선 위에서 설명한 키워드라고 생략했는데, 추가적인 설명과 예가 있으면 좋을것같아요.
예를들어 캐싱할 수 없는 조건인 사용자 변수가 들어간 UNION 테이블을 보여주거나 하면 더 좋을것같네요

**Comment by pci2676** [comment]
`UNION`은 서로다른 SELECT 의 결과가 같은 컬럼을 반환 할 때 그 결과를 합쳐서 보여주는 것을 의미해.
`UNCACHEABLE`은 말그대로 캐시 할 수 없다는 것을 의미하지. 매번 쿼리를 실행할 때 마다 값이 달라지는 경우 앞의 키워드가 붙게된다고 생각하면 될 것 같아!

아래는 예시 쿼리야. `SELECT` 하는 컬럼에 `RAND()`라는 호출 할 때 마다 결과 값이 달라지는 함수가 포함되어 있는 것을 잘 보면 될 것 같아.
### 쿼리
```sql
EXPLAIN
SELECT emp_no, RAND() AS RANDOM FROM salaries WHERE salary>100000
UNION ALL
SELECT emp_no, RAND() AS RANDOM FROM dept_emp WHERE from_date>'2020-12-07'
```

### 결과
![image](https://user-images.githubusercontent.com/13347548/99885048-98209500-2c75-11eb-9670-b7b890a4b8ca.png)

`RAND()` 를 사용함에 따라서 캐싱할 수 없는 조건이 생겨나면서 `UNCACHEABLE UNION` 으로 분석 결과가 나오는 것을 확인 할 수 있어!
