### ISSUE TITLE
[6-3장] 데이터 웨어하우스 용어 설명

### ISSUE THREAD

**Issue by pci2676** [gazi-gazi/real-mysql#20]
> `p.331` 데이터 웨어하우스용으로 MySQL을 사용한다면...

질문 : 데이터 웨어하우스 라는 용어가 자주 등장하는 것 같은데 용어에 대한 설명 해주면 좋을듯!

**Comment by toneyparky** [comment]
#17 에 작성해둔 답변으로 대체하겠습니다😬
[관련 링크](https://github.com/gazi-gazi/real-mysql/issues/17#issuecomment-736255849)
