### ISSUE TITLE
[6-3장] 인덱스를 이용한 정렬

### ISSUE THREAD

**Issue by pci2676** [gazi-gazi/real-mysql#21]
> `p.339` 인덱스를 이용한 정렬

질문 : 인덱스를 이용해서 정렬이 가능한 경우랑 불가능한 경우 나눠서 정리해주면 좋을것 같아. 만약 md로 따로 정리할거면 그 md링크 걸어주면 좋을듯

**Comment by jjj0611** [comment]
질문 🙅‍♂️ 요청 🙆‍♂️

정리 올리는 부분에 이거에 대한 부분 같이 정리해놨어~
곧 올릴게~
