### ISSUE TITLE
[6-3장] 네스티드 루프

### ISSUE THREAD

**Issue by yebink** [gazi-gazi/real-mysql#22]
> `p.339` 조인이 네스티드 루프 방식으로 실행된다.

질문 :
네스티드 루프가 어떤 방식인지 설명해주세요.
아래 설명처럼 드라이빙 테이블을 먼저 정렬하는 방식을 뜻하나요?

**Comment by toneyparky** [comment]
`네스티드-루프`에 대한 설명은 `FOR`나 `WHILE` 같은 반복 루프 문장을 두 개 실행하는 형태로 조인을 하는 것을 말합니다. 
말 그대로 루프 문장이 중첩된 형태로 조인을 하는 것이죠.

`아우터 테이블`을 `드라이빙 테이블`이라 하고 `이너 테이블`을 `드리븐 테이블`이라고 한다고 합니다. 
또한 말씀해주신 것 처럼` 아우터 테이블`을 `이너 테이블`보다 먼저 읽어야 합니다. 

~~~SQL
FOR ( record1 IN TABLE1 ) {         // 외부 루프 (OUTER)
    FOR ( record2 IN TABLE2 ) {    // 내부 루프 (INNER)
        IF ( record1.join_column == record2_join_column ) {
            join_record_found( record1.*, record2.*);
        } else {
            join_record_not_found();
        }
    }    
}
~~~
위의 수도 코드는 `네스티드-루프`로 처리되는 `INNER JOIN`의 내부 동작을 나타낸 것입니다. 


더 자세한 설명은 책을 더 읽다보면 `p.359`에 관련 내용이 나옵니다.
책에서는 `MySQL`은 `네스티드-루프` 방식만으로 조인을 진행한다고 설명하네요🙂

**Comment by jjj0611** [comment]
p. 359부터 네스티드 루프에 대한 설명이 나오는데
그것까지 안 읽으신거군요!

**Comment by yebink** [comment]
@jjj0611 그러니까 말입니다! 방금 읽었네요

고마워요 @toneyparky !! 설명이 이해가 쏙 쏙 되었어요~
