### ISSUE TITLE
[6-3장] 루스 인덱스 스캔의 최적화

### ISSUE THREAD

**Issue by giantim** [gazi-gazi/real-mysql#23]
> `p.349` 참고: ... 오라클과 같은 DBMS에서는 옵티마이저가 인덱스의 첫 번째 칼럼에 대한 조건을 마음대로 만들어서 추가하는 형태로 이런 기능이 구현돼 있다. 하지만 지금 출시하는 MySQL 5.0, 5.1 그리고 5.5에서는 아직 루스 인덱스 스캔이 이렇게 인덱스를 사용할 수 있는 방법은 지원되지 않는다.

질문 : 책에서 설명하는 버전이 너무 구버전이랑 지금 우리가 도커로 사용하는 5.7 버전이나 그 이상의 버전에서는 루스 인덱스 스캔이 최적화가 되어 있는지 궁금하네요 :)

**Comment by jjj0611** [comment]
이 부분에 대해서 이것저것 좀 찾아봤는데, 딱히 이것을 최적화 했다는 이야기는 별로 없었네요.
그래서 MySQL 8.0 version [레퍼런스](https://dev.mysql.com/doc/refman/8.0/en/group-by-optimization.html#loose-index-scan)를 조금 찾아봤어요.

일단 질문 중 인용구에서 루스 인덱스 스캔은 인덱스의 첫 번째 칼럼이 WHERE 조건이나 GROUP BY에 사용되지 않아도 B-Tree 인덱스를 사용할 수 있는 방식이다. 오라클과 같은 DBMS에서는 옵티마이저가 인덱스의 첫번째 칼럼에 대한 조건을 마음대로 만들어서 추가하는 형태로 기능이 구현되어 있다. 근데 MySQL에서는 안된다.

p.349 위에서 인덱스 구성 칼럼이 왼쪽부터 일치하지 않기 때문에 사용불가라는 이야기가 나와요.

그리고 저 위의 레퍼런스를 보면 loose index scan을 사용할 수 없는 쿼리에 여전히 위와 같은 내용은 불가능하다고 나오는걸 보면
아마 8.0에서도 이런 부분에 대한 변경은 없었다고 생각이 돼요.

근데 이게 그냥 유추한 내용이기 때문에 정확한 정보는 아니라 한 번 보고 어떻게 생각하는지 얘기해봐요~
