### ISSUE TITLE
[6-3장] 정렬의 처리방식

### ISSUE THREAD

**Issue by yebink** [gazi-gazi/real-mysql#24]
> `p.345` 표

질문 :
tb_test2가 드라이빙 테이블인 경우에서 **읽어야 할 건수** 부분이 이해가 안 가요.
참고할만한 설명을 붙여주면 좋을 것 같아요.

**Comment by giantim** [comment]
t1 레코드: 100건
t2 레코드: 1000건
t1 레코드 1건당 t2 10건씩 존재

**인덱스 사용**
이미 인덱스로 정렬이 되어 있으므로 정렬해야 할 대상 0건 -> t2 레코드 1건당 조인 한 번씩 10번을 해야 함 -> 조인 횟수 10번 -> 즉 t2 레코드 1건당 t1 레코드 1건씩 읽어야 해서 각각 10건씩 읽는다.

**드라이빙 테이블만 정렬**
t2를 정렬해야 하므로 t2의 1000건 레코드를 t1과 조인하지 않고 모두 정렬한다. 그 후에 t2 레코드 10건에 대하여 조인한 t1 10건만 읽으면 된다.

**임시 테이블을 사용한 후 정렬**
주어진 쿼리문은 드리븐 테이블(t1)의 컬럼을 정렬 조건으로 사용하므로 임시 테이블을 사용해서 정렬할 것이다. 임시 테이블을 사용한 후 정렬하려면 조인한 결과를 정렬한 후에 결과값을 반환해야 한다. 즉 조인이 선행되야 하므로 t2 레코드 1000건에 대해 t1과 먼저 조인한다. 조인이 선행되야 하므로 t1 레코드 100건을 모두 읽게 되는 것이다.

저는 이렇게 이해했는데 어떻게 생각하시나요!

**Comment by jjj0611** [comment]
라빈 설명 굿~

인덱스 사용 -> 인덱스만으로 정렬한다.
드라이빙 테이블만 정렬 -> 드라이빙 테이블로만 정렬
임시 테이블 사용한 후 정렬 -> 조인해서 만들어진 임시테이블에서 정렬

인덱스로만 정렬시
test2 테이블의 인덱스를 사용해서 LIMIT 10건만 읽으면 됨(읽어야 할 건수 10) 
test1 테이블은 test2에서 읽어진 10개에 대해서 join하기 위한 10건만 읽으면 됨(읽어야할 건수 10)

드라이빙 테이블만 정렬
test2 테이블에서 인덱스를 사용하지 않고 정렬해야 하므로 1000건을 다 읽어서 정렬해야함(읽어야 할 건수 1000) 그 중 10개 뽑음
test1테이블에서는 test2에서 뽑아진 10개에 대해 조인만 하면 되므로 10개만 읽으면 됨.

임시 테이블 사용
test2와 test1을 조인한 상태로 임시 테이블을 만들어야 하므로 test2 1000건을 모두 읽어서 test1에 조인해야 함.
test2를 기준으로 조인하기 때문에 조인 횟수 1000건 조인을 해서 임시테이블을 생성해야하므로 test1 100건 조회 후 조인
그럼 1000건의 레코드가 임시테이블에 있기 때문에 1000번의 정렬을 해야함.

**Comment by yebink** [comment]
둘다 설명 굿굿!
내가 헷갈린 부분이 쿼리에서 `ORDER BY t1.col2`인데 그럼 
t2가 드라이빙이면서 인덱스를 사용할 경우에는 쿼리가 `ORDER BY t2.col2`이고 col2는 인덱스 컬럼이라고 봐야 하는거야?

**Comment by jjj0611** [comment]
오 맞지 맞지
내 생각엔 저 쿼리 하나로 6가지 경우의 수를 다 커버하는게 아니라 6가지 경우의 수를 설명하기 위한 샘플로서 주어진 쿼리인 것 같아. 여기서는 6가지 경우의 수가 각각 어떤 쿼리냐보다 어떤 상황이냐가 중요한거니 쿼리는 하나만 보여주고 상황에 대한 설명만 한 것으로 생각 돼!

**Comment by yebink** [comment]
아 굿굿 이해 너무 잘됨 👍
