### ISSUE TITLE
[5-2장] 전문 검색에 사용되는 인덱스

### ISSUE THREAD

**Issue by begaonnuri** [gazi-gazi/real-mysql#26]
> `p.208` 전문 검색과 같은 특수한 요건이 아닌 경우, 대부분 인덱스는 거의 B-Tree를 사용할 정도로 일반적인 용도에 적합한 알고리즘이다.

질문 : 실행 계획에서 전문 검색 역시 인덱스를 사용한다고 학습했는데, 이 경우엔 B-Tree 말고 어떤 인덱스를 사용하는걸까?!
그리고 Hash 인덱스를 제외하면 값의 부분 일치 검색이 가능해서 텍스트 검색도 가능할텐데 B-Tree를 사용하지 않은 이유는 무엇일까?

**Comment by jjj0611** [comment]
전문 검색 인덱스는 p.244에 나와서 그 부분을 보게 되면 좋을 것 같고,
B-Tree 같은 경우에는 값의 부분 일치 검색이 가능은 하지만, 컬럼의 왼쪽부터 일치해야하기 때문에 적절하지 않은 것 같아.
예를 들어 '터틀'이라는 키워드가 들어간 문서를 찾는데, B-Tree를 사용할 경우 '터틀'로 시작하는 것만 찾을 수 있으니까!

**Comment by lxxjn0** [comment]
전문 검색에 대해 간략하게 설명하면 전문 검색은 전문적인 검색이 아니라 전체 문장을 검색한다는 Full Text search였어!

`p.244` 에 간단하게 설명된 바로는 B-Tree 인덱스의 경우 스토리지 엔진에 따라 최대 1000바이트까지만 잘라서 인덱스로 사용하는데, 이때 컬럼 좌측부터 잘리게 되서 전체 문장을 검색하는 것에는 무리가 있는 것 같아.

또 내 생각일 수 있지만 전체 문장을 인덱스로 사용한다면 키 값의 크기가 매우 커질거야(전체 문장이 키 값이 되니까?). 그런데 B-Tree 인덱스는 키 값이 커지면 트리의 깊이가 깊어지게 되고 이는 검색을 할 때 성능상의 손해를 가져오게 돼. 그래서 전문 검색의 경우 B-Tree 인덱스를 안쓰는게 아닐까?나?
