### ISSUE TITLE
[5.3.2장] B-Tree 인덱스 키 추가 및 삭제(인덱스 키 추가)

### ISSUE THREAD

**Issue by jjj0611** [gazi-gazi/real-mysql#28]
> `p.212` MySQL 5.5 이상의 버전에서는 INSERT뿐 아니라 DELETE 등에 의한 인덱스 키의 추가 및 삭제 작업까지 버퍼링해서 지연 처리할 수 있게 기능이 확장 됐다.

> `p.212` MySQL 5.5이상 버전부터는 "innodb_change_buffering" 설정 값을 이용해 키 추가 작업과 키 삭제 작업 중 어느 것을 지연 처리할지 설정해야 한다.

질문 : 위 부분을 보면 두 개 모두 버퍼링해서 지연처리 해줄 수 있는 것 같은데, 아래 내용에는 뭔가 둘 중 하나를 선택해야하는 것처럼 나와 있는 것 같아요~ 아마 둘 다 한 번에 처리 가능할거 같아서 "innodb_change_buffering"에 어떤 값들을 넣어주냐에 따라 선택 가능한 것으로 보여지는데 "innodb_change_buffering" 설정하는 거 보여주면 좋을 것 같아요~ 그리고 이게 실제로 작동하는 것까지 볼 수 있으면 너무 좋을듯?(어렵겠지만...)

**Comment by lxxjn0** [comment]
먼저 변경 버퍼(change buffer)에 대해 이야기하고 시작할게요(제가 이 부분이 이해가 잘 안갔거든요...)

![image](https://user-images.githubusercontent.com/48052622/102012155-08f63100-3d8c-11eb-9678-f2552652aca0.png)

innoDB에서는 테이블 및 인덱스 데이터를 캐싱하는 버퍼 풀이 있습니다. 자주 사용하는 데이터를 메모리에 올려두면 빠른 속도로 이용할 수 있기 때문입니다. 그런데 만약 새로운 인덱스의 변경 사항이 생겼는데, 이를 적용할 페이지가 버퍼 풀에 없다면 어떻게 해야 할까요? 새로운 페이지를 버퍼 풀로 가져와서 변경된 인덱스를 적용해야 할 것입니다. 이는 I/O 작업이 발생하기 때문에 성능상에 손해가 생기게 되죠. 이럴때 사용 되는 것이 변경 버퍼입니다.  변경 사항을 적용할 페이지가 버퍼 풀에 없을 경우 변경 버퍼에 저장을 해 두고 나중에 다른 읽기 조작으로 페이지를 버퍼 풀에 로드할 때 병합합니다.

`innodb_change_buffering`은 이 변경 버퍼에 어떠한 데이터를 캐싱할 지 관리하는 변수입니다. INSERT, UPDATE, DELETE 작업을 수행할 때 주로 인덱스에 대한 변경이 발생하므로 이 작업들에 대해 설정 가능합니다.

`innodb_change_buffering`의 기본 값은 all입니다. 허용되는 값은 아래에 나열해 두겠습니다.

- all : buffer inserts, delete-marking operations, and purges

- none: 작업을 버퍼링하지 않는 것

- inserts : 버퍼 삽입 작업

- deletes : 버퍼 삭제 표시 작업

- changes : 삽입 및 삭제 표시 작업을 모두 버퍼링

- purges : 백그라운드에서 발생하는 버퍼 물리적 삭제 작업

해당 속성은 MySQL 옵션 파일(my.cnf 또는 my.ini)에서 설정하거나 SET GLOBAL 문을 통해 동적으로 변경할 수 있습니다. 추가적으로 `innodb_change_buffer_max_size` 변수로 변경 버퍼의 최대 크기도 조절할 수 있습니다. 

![image](https://user-images.githubusercontent.com/48052622/102013081-22e64280-3d91-11eb-99a3-9a8da3efe5bc.png)

작동하는 걸 어떻게 보여줄 수 있을지 찾아봤는데 방법이 마땅치 않아서.. ㅜㅜ 위에는 우리가 쓰는 디비에 변수 값이 어떻게 설정되어 있는지 보여주는 거야!!

> 참고 : [[MySQL][InnoDB] 메모리 구조](https://myinfrabox.tistory.com/46)
