### ISSUE TITLE
[5.3.2장] B-Tree 인덱스 키 추가 및 삭제 (인덱스 검색)

### ISSUE THREAD

**Issue by jjj0611** [gazi-gazi/real-mysql#29]
> `p.214` 따라서 UPDATE나 DELETE 문장이 실행될 때 테이블에 적절히 사용할 수 있는 인덱스가 없으면 불필요하게 많은 레코드를 잠근다.

질문 : `p.213` 하단부를 보면 InnoDB 테이블에서 지원하는 레코드 잠금이나 넥스트 키 락(갭 락)이 검색을 수행한 인덱스를 잠근 후 테이블의 레코드를 잠그는 방식으로 구현돼 있다고 하면서 해당 내용이 나오기 시작했는데, 여기서 불필요하게 많은 레코드를 잠근다는 것이 왜 나온걸까? 인덱스를 잠근다 -> 레코드를 잠근다. 언제? 테이블에 적절히 사용할 인덱스가 없을 때. 즉, `DELETE FROM test_db WHERE name='스티치';`이런 쿼리문에서 name에 index가 안 걸려 있는 경우밖에 생각이 안드는데, 그럼 이 경우에는 인덱스를 잠그고 -> 레코드를 잠근다가
1) 테이블 풀 스캔을 해서 name이 스티치인 것을 찾아서 잠그고 삭제한다.
2) 적절한 인덱스로 잠글 수 없으므로 test_db 테이블을 모두 잠그고 name이 스티치인 것을 찾아가며 지운다.

이 두 가지 중 아마 2번일 확률이 높을 것 같은데(불 필요하게 많은 레코드를 잠근다고 했으므로) 실제로 이렇게 동작하는 것인지? 즉, 불필요하게 많은 레코드를 잠글 수 있다는 것의 의미가 2번과 같은 것이 맞을지 그렇다면 실제로 테이블이 잠기는 것을 볼 수 있으면 좋을 것 같고, 2번이 아니라면 어떤의미인지 예시와 함께 볼 수 있으면 좋을 것 같아요~

**Comment by lxxjn0** [comment]
먼저 형의 추측은 정답~~~ 💯 

`p.181`에 인덱스와 잠금을 보면 보다 자세하게 설명이 돼있어!

InnoDB는 변경해야 할 레코드를 찾기 위해 검색한 인덱스의 레코드를 모두 잠궈버려. 즉, 검색할 대상이 된 모든 레코드는 잠겨버리는거지! 먼저 책에 있는 예시를 통해 간단히 설명하도록 하겠습니다~

`employees` 테이블은 `first_name` 칼럼을 인덱스로 가지고 있고 `last_name`은 인덱스로 가지고 있지 않아.

![image](https://user-images.githubusercontent.com/48052622/102014377-f3d3cf00-3d98-11eb-85c6-727e8150d8ae.png)

![image](https://user-images.githubusercontent.com/48052622/102014405-1ebe2300-3d99-11eb-9697-bca829570748.png)

여기서 

```mysql
update employees
set hire_date=now()
where first_name = 'Georgi'
  and last_name = 'Klassen';
```

쿼리를 실행하면 어떻게 될까?

변경할 대상은 앞서 본 결과와 같이 레코드 1건에 불과하지만 쿼리에서 검색 조건으로 사용한 `first_name='George'` 인 레코드는 253건이야. 즉, InnoDB에서는 이 쿼리가 실행될 때, 인덱스로 검색된 253건의 레코드가 모두 잠기게 돼.

그렇다면 물어본 것 처럼 인덱스가 없는 경우는? 당연히 풀 테이블 스캔을 하면서 검색 조건으로 모든 레코드가 사용되게 되고 이 과정에서 테이블의 30여 만 건의 모든 레코드는 잠기게 돼(`p.182` 참고)

이처럼 불필요한 레코드의 잠금 현상은 InnoDB의 넥스트 키 락 때문이라는데 이건 4장을 공부할 때 확인하면 될 것 같어!

마지막으로 그럼 실제로 테이블이 잠기는 지 확인해보도록 하겠으.

![image](https://user-images.githubusercontent.com/48052622/102015115-f7695500-3d9c-11eb-9153-2f9401e4241e.png)

이 조건은 먼저 동일한 테이블의 레코드를 접근하는 두 개의 쿼리를 다른 세션에서 동작 시켰어.

```mysql
# session 1

begin; # 트랜잭션 시작

update employees
set hire_date=now()
where first_name = 'Georgi'
  and last_name = 'Klassen';
```

```mysql
# session 2

update employees
set hire_date=now()
where first_name = 'Georgi'
  and last_name = 'Klassen';
```

첫 번째 세션의 트랜잭션을 열고 쿼리를 실행시켰어. 그리고 두 번째 세션의 쿼리를 실행시키면 접근해야 하는 레코드가 겹치기 때문에 계속 block 상태로 기다리게 돼.

![image](https://user-images.githubusercontent.com/48052622/102015130-0f40d900-3d9d-11eb-824d-c30b93a853c6.png)

먼저 `INNODB_LOCK_WAITS` 는 현재 wait으로 대기하고 있는 session에 대해 나타내줘.

- `requesting_trx_id` 가 요청한 트랜잭션(3861), block 당한 트랜잭션이고

- `blocking_trx_id` 가 현재 실행 중인 트랜잭션(3860), block 하고 있는 트랜잭션이야.

![image](https://user-images.githubusercontent.com/48052622/102015158-2d0e3e00-3d9d-11eb-8a29-3d2a9aeda318.png)

`INNODB_LOCKS` 는 현재 lock 정보를 보여줘.

- 트랜잭션 3861가 lock을 lock_mode X (X는 수정, S는 읽기), lock_type RECODE 로 `rms`, `employees` 테이블의 `ix_first_name` 인덱스 에 걸었다는 것. 이후는 크게 중요하지 않은 것 같고 lock_data는 insert 하려는 pk의 값(인덱스 락이라 추가적으로 인덱스가 나온 것 같어)이야.

- 트랜잭션 3860도 같은 느낌!

![image](https://user-images.githubusercontent.com/48052622/102015171-46af8580-3d9d-11eb-99d4-5a118844508b.png)

![image](https://user-images.githubusercontent.com/48052622/102015181-55963800-3d9d-11eb-83f8-55f001dead89.png)

- 트랜잭션 3861이 LOCK WAIT이고 `trx_query`를 보면 어떤 쿼리인지 알 수 있어.

- 트랜잭션 3860은 RUNNING이고 나머진 마찬가지

그리고 마지막으로 동일한 테이블에 인덱스를 없애서 테스트해보고 싶었는데 잘 안되서 이건 따로 시도해보진 못했어..ㅜㅜ 나중에 따로 테이블을 하나 만들어서 실험해보면 좋을 것 같아!! 그럼~~

> 참고 : [information_schema.INNODB_XXX 를 활용한 lock 정보 확인 - MIN CHO](http://minsql.com/mysql/information_schema.INNODB_XXX-%EB%A5%BC-%ED%99%9C%EC%9A%A9%ED%95%9C-lock-%EC%A0%95%EB%B3%B4-%ED%99%95%EC%9D%B8/)

**Comment by giantim** [comment]
동일하게 ```employees``` 테이블로 실험해보겠습니다.

```sql
alter table employees drop index ix_firstname;
alter table employees drop index ix_hiredate;
```
위의 쿼리를 실행해서 ```first_name, hire_date```로 생성되었던 인덱스를 모두 삭제하겠습니다.

```sql
select count(first_name) from employees where first_name = 'Georgi';
```
먼저 위의 쿼리를 실행해보면 ```first_name = 'Georgi'```인 데이터는 253건임을 알 수 있습니다.

하나의 세션에서는 ```first_name = 'Georgi'```인 데이터를 삭제하고 다른 세션에서는 ```first_name <> 'Georgi'(<> == !=)```인 데이터를 삭제해 보겠습니다.

- 첫 번째 세션
```sql
start transaction;

delete from employees where first_name = 'Georgi';
```

- 두 번째 세션
```sql
start transaction;

delete from employees where first_name <> 'Georgi';
```

두 쿼리를 실행한 후 트랜잭션의 블락 상황에 대해 살펴보겠습니다. 스티치가 설명한 락 정보에 대한 실행 쿼리는 아래와 같습니다.
```sql
select * from information_schema.INNODB_LOCK_WAITS; -- 현재 wait으로 대기하고 있는 세션

select * FROM information_schema.INNODB_LOCKS; -- 현재 lock 정보

select * FROM information_schema.INNODB_TRX; -- 해당 lock을 걸고 있는 트랜잭션의 상태
```

![image](https://user-images.githubusercontent.com/39546083/102055251-e74d8600-3e2d-11eb-98e6-63a4df7d0857.png)

삭제 쿼리의 조건절에 대해 적절한 인덱스로 데이터만 따로 잠글 수 없으므로 테이블에 있는 전체 데이터를 잠궈서 트랜잭션이 블락된 모습입니다.
