### ISSUE TITLE
[5.4장] 해시(Hash) 인덱스

### ISSUE THREAD

**Issue by jjj0611** [gazi-gazi/real-mysql#30]
> `p.233` 해시 인덱스는 주로 메모리 기반의 테이블에서 주로 사용되지만 기본적인 특성은 반드시 알아두자.

요청 : 1) 해시 인덱스가 주로 사용되는 메모리 기반의 테이블이 어던 것들이 있는지 감이 안오는데 이 부분을 찾아줄 수 있을까? 또 바로 위에 InnoDB의 버퍼 풀에서 빠른 레코드 검색을 위한 어댑티브 해시 인덱스로 사용되기도 하고, 오라클과 같은 DBMS에서 조인에 사용되기도 한다는데, 2) InnoDB의 버퍼 풀에서 사용된다는 것이 어떤 의미 인지, 그리고 오라클에서는 조인에 사용된다고 하는데 MySQL에서는 사용되지 않는지? 오라클에서 조인에 어떻게 활용되는지 설명이 있으면 좋을 것 같아! 마지막으로 3) `p.235`에서 InnoDB 스토리지 엔진에서는 해시 인덱스를 지원하지 않지만, 인위적으로 해시 함수를 만들어 해시 인덱스처럼 사용해야 하는 경우가 있다고 했는데 주로 어떨 때 사용할까?

**Comment by giantim** [comment]
[오라클에서 사용하는 해시 조인에 대해서 저도 궁금해서 아주아주 간단하게만 찾아봤습니다.](http://ojc.asia/bbs/board.php?bo_table=LecHINT&wr_id=127)
오라클에서 해시 조건을 사용하는 조건을 간단하게만 적으면

1. 조인 컬럼에 적당한 인덱스가 없어 NL조인이 비효율적일때
2. 조인 컬럼에 인덱스가 있더라고 NL 조인 드라이빙 집합에서 Inner 쪽 집합으로서의 조인 액세스량이 많아 Random 액세스 부하가 심할 때

라고 합니다.

MySQL에서는 8.0 버전 이상 부터 해시 조인을 지원하고 있다고 합니다. [공식 문서에서 해시 조인에 대한 설명이 있으니 한번 읽어보셔도 좋을 것 같네요 :)](https://dev.mysql.com/doc/refman/8.0/en/hash-joins.html)

간단하게 요약하면 해시 조인은 조인 구문을 옵티마이저가 분석한 후 적용하는것 같습니다. 해시 조인의 경우 메모리를 사용하기 때문에 해시 조인에 사용하도록 지정한 메모리양 보다 조인할 데이터의 크기가 더 커버리면 디스크를 이용해서 작업을 처리한다고 합니다. 그래서 너무 큰 데이터를 조인하면 과거 버전과 마찬가지로 BNL(block nested loop)로 조인을 처리한다고 합니다.

[MySQL의 해시 조인에 대한 예시는 여기를 참고해보시면 좋을 것 같네요 :)](https://sarc.io/index.php/mariadb/1768-mysql-8-0-18-hash-join)

**Comment by ghost** [comment]
# 1. 메모리 기반의 테이블이란?

## 인메모리 테이블이란?

- 메모리와 디스크 양 쪽의 복사본이 있는 테이블

### 장점

- 일반 테이블과는 다르게 업데이트된 데이터 행의 어떤 버전에도 잠금이나 래치를 적용하지 않는다.
    - 낙관적 접근 방식 사용
    - contention(경합)을 줄이고 트랜잭션을 기하급수적으로 빠르게 처리할 수 있다.
    - 잠금 대신 메모리 내에서 버전을 사용하여 트랜잭션이 커밋될 때까지 원래 행을 유지
    - 페이지가 없고 그저 행단위로 저장된다.

- 활성 메모리 내부의 속도에 최적화되어 워크로드에 따라 상당한 성능 향상!

- 임시 테이블을 처리하는 것보다 효율적으로 사용 가능하다.
- 왜 임시 테이블보다 인메모리 테이블이 더 효율적인가?

- 이런 테이블은 대용량 읽기보다 대용량 쓰기에서 훨씬 더 효율적이다.

MOA (Memory Optimization Advisor) 라는 도구를 사용하면 메모리 내에서 이점을 얻을 수 있는 테이블을 쉽게 결정할 수 있다. 

- You have two options for the second index. You can use a NONCLUSTERED INDEX which is great for tables with many range queries and needing a sort order or you can use a NONCLUSTERED HASH index which is better for those direct lookups.
- 두 번째 인덱스에 대한 옵션이 두 개 있습니다. 다양한 범위 쿼리가 있는 테이블에 좋고 정렬 순서가 필요한 비클러스터 인덱스를 사용하거나 직접 룩업에 더 좋은 비클러스터 HASH 인덱스를 사용할 수 있다.

# 2. 해시 인덱스가 메모리 기반의 테이블에서 사용되는 이유?

# 3. InnoDB 버퍼 풀에서 빠른 레코드 검색을 위한 어댑티브 해시 인덱스로 사용되는 이유?

 InnoDB 버퍼 풀에서 B-Tree가 대표적인 인덱스이다. 데이터는 PK순으로 정렬되어 관리되고 보조키들의 경우 인덱스키 + PK를 조합으로 정렬돼있다.

 즉, 특정 데이터를 찾기 위해서는 Secondrary Key에서 PK를 찾고, 그 PK를 통해 다시 원하는 데이터로 찾아가는 형태로 데이터가 처리된다. 트리의 가장 큰 강점은 데이터 접근 퍼포먼스가 데이터 증가량에 따라서도 결코 선형적으로 증가하지 않다는 점에 있다

 참고로, PK 접근 시 데이터 접근에 소요되는 비용은 `O(logN)`이고,두번 트리에 접근하는 Secondrary Key에 소요되는 비용은 `2 * O(logN)`이다.

- 데이터가 아무리 많아져도, 데이터 접근에 소요되는 비용이 크게 증가되지 않음에도, 상황에 따라 효율이 좋지 않다. **자주 사용되는 데이터 탐색에도 매번 트리의 경로를 쫓아가야한다.** 게다가 Mutex Lock이 과도하게 잡히게 되면, 적은 데이터 셋에도 불구하고 DB 자원 사용 효율이 떨어지게된다.

그래서 나왔다. Adaptive Hash Index!

자주 사용되는 칼럼을 해시로 정의하여, B-Tree를 타지 않고 바로 데이터에 접근할 수 있는 기능

"Adaptive" 라는 말처럼 모든 값들이 해시로 생성되는 것이 아니라, 자주 사용되는 데이터 값만 내부적으로 판단하여 상황에 맞게 해시 값을 생성

- 그래서, 질문의 답은 범위 검색이 아닌 단건 조회의 경우 Hash 알고리즘을 사용하면 B-Tree 탐색 처럼 Secondary Index를 타고 PK(index) 를 타는 이런 경우를 한번으로 조회가 가능하므로 성능이 향상된다.

# 4. 오라클에서 조인에 해쉬 인덱스가 어떻게 활용되는지

# 5. 오라클과 같은 DBMS에서 조인에 사용되는데 MySQL에서는 사용되는지?

# 6. InnoDB 스토리지 엔진에서는 해시 인덱스를 지원하지 않지만, 인위적으로 해시 함수를 만들어 해시 인덱스처럼 사용해야 하는 경우는 어떤 경우인가?

**'큰 문자열 칼럼의 인덱스'**

가끔 매우 긴 문자열을 저장하는 칼럼에 대해 인덱스를 생성하거나 검색을 수행해야할 때가 있다. 이러한 요건은 주로 URL 정보를 관리할 때 필요한데, 일반적으로 URL 정보는 인덱스 생성 시 상당히 부담스러운 사이즈의 데이터이다.

- 인덱스 키의 사이즈가 크면 성능이 떨어진다는 내용은 책에서 다룬다.

 InnoDB의 테이블 인덱스는 하나의 레코드가 767 바이트 이상을 넘을 수 없다. 이떄는 칼럼의 앞 부분 767 바이트만 잘라서 PK, UK로 생성할 수 있는데, 이를 **프리 픽스 인덱스**라 한다.

 이 때 PK나 UK는 당연하게도 키가 중복되면 안되므로 앞의 프리픽스인 767 바이트가 중복되는 경우가 발생할 수도 있다. 이럴 때는 긴 문자열의 해쉬 값으로 프라이머리 키나 유니크 인덱스를 생성하는 방법을 사용한다.

- 즉, 해쉬 테이블 처럼 1 depth로 데이터에 접근하는 방식이 아닌 해쉬 알고리즘을 사용해 key에 저장하는 방식이 해쉬 인덱스처럼 사용된다고 일컫는 것이라고 판단된다.

**Comment by ghost** [comment]
### 래치란 무엇인가?

Latch란 **오라클**에서 Lock와 함께 잠금에 사용되는 장치이다. 

### Lock과의 차이점
- Lock보다 가볍다.
- SGA 내부의 공유 데이터에 대한 배타적인 잠금을 보장하는 장치이다.
   - SGA는 오라클 내부에서 서버 프로세스들이 공유할 수 있는 공유 메모리이다.

### Lock의 특징
- 메모리 구조의 무결성을 유지하도록 하는 것
- 한 순간에 하나의 프로세스만이 latch를 보유할 수 있따.
- SGA에 접근하는 모든 프로세스는 반드시 해당 영역을 관장하는 Latch를 획득해야지만 접근이 가능

> 이 시점에서는 그냥 Latch가 오라클에서 사용되며 Lock보다는 가볍고 메모리 구조의 프로세스 단위의 무결성을 유지하기 위한 장치 라고만 알고 있으면 될 것 같아.

**Comment by ghost** [comment]
> 책에서는 NL조인 내용을 못찾았는데 찾은 분 있으면 공유 좀 해주세요~

### NL 조인이란?

- 2개 이상의 테이블에서 하나의 집합을 기준으로 순차적으로 상대방 row를 결합하여 원하는 결과를 조합하는 방식
- 먼저 선행 테이블의 처리 범위를 하나씩 액세스하면서 추출된 값으로 연결할 테이블을 조인한다.

쉽게 생각하면 아래와 같이 조인이 실행된다고 생각하면 된다.

```
< C, JAVA >
 for(i=0; i<100; i++) { -- outer loop 
   for(j=0; j<100; j++) { -- inner loop 
   // Do Anything ... 
   } 
}
```

선행 테이블(외부 테이블): 반복문의 외부에 있는 테이블
후행 테이블(내부 테이블): 반복문의 내부에 있는 테이블

### NL join 특징
- 선행 테이블에서 만족하는 행을 추출 후 후행 테이블을 읽으면서 조인 수행
- 선행 테이블에 만족하는 행의 수만큼 반복
- 선행 테이블의 만족하는 수만큼 조인이 반복됨으로 선행 테이블의 행의 수가 적은 것이 유리
- 랜덤 액세스 방식이기 때문에 처리 범위가 좁은 것이 유리

### NL 조인 방법
 1. 선행 테이블에서 주어진 조건을 만족하는 행을 찾는다.
 2. 선행 테이블에서 조인 키 값을 가지고 후행 테이블에서 조인 수행
 3. 선행 테이블의 조건을 만족하는 모든 행에 대해 1번 작업 반복 수행

![image](https://user-images.githubusercontent.com/34959979/102623004-2b6dbd00-4185-11eb-8e5d-be1188023839.png)

그림예제를 통한 표현
 
⓵ 선행테이블에서 조건을 만족하는 첫 번쨰 행을 찾음
→이때 선행 테이블에 주어진 조건을 만족하지 않는 경우 해당 데이터는 필터링을 됨
⓶ 선행 테이블의 조인키를 가지고 후행 테이블에 조인 키가 존재하는지 찾으러감
→조인시도
⓷ 후행테이블의 인덱스에 선행 테이블의 조인 키가 존재하는지 확인
→선행 테이블의 조인 값이 후행 테이블에 존재하지 않으면 선행 테이블 데이터는 필터링
(더이상 조인작업을 진행할 필요가 없음)
④ 인덱스에서 추출한 레코드 식별자를 이용하여 후행 테이블을 엑세스
→인덱스 스캔을 통한 테이블 엑세스
후행 테이블에 주어진 조건까지 만족하면 해당 행을 추출버퍼에 넣음
⑤ ~⑪ 앞의 작업을 반복
 
추출버퍼 : SQL의 실행결과를 보관하는 버퍼로써 추출버퍼에 결과가 모두 차거나 더 이상 결
과가 없어 추출버퍼를 채울것이 없으면 결과를 사용자에게 반환

> Nested Loop의 특징
- 좁은 범위에 유리한 성능을 보여줌
- 순차적으로 처리하며, Random access 위주
- 후행 테이블(Driven) 에는 조인을 위한 인덱스 생성 필요
- 실행 속도 = 선행 테이블 사이즈 * 후행 테이블 접근 횟수

### NL 조인 사용법 예제 및 실행 계획

![image](https://user-images.githubusercontent.com/34959979/102623175-71c31c00-4185-11eb-8b8a-73ea50850fdb.png)

### NL 사용시 주의 사항
- 데이터를 랜덤으로 액세스하기 때문에 결과 집합이 많으면 느려진다.
- Join index가 없거나, 조인 집합을 구성하는 검색 조건이 조인 범위를 줄여주지 못할 경우 비효율적
- 테이블 중 row 수가 적은 쪽을 Driven 테이블로 설정하는 것이 좋다.
- 만족하는 조건이 적은 쪽을 Driving 테이블로 설정하는 것이 좋다.

[링크](http://www.dbguide.net/db.db?boardConfigUid=9&boardIdx=136&boardStep=1&boardUid=148210&categoryUid=216&cmd=view)에 잘 나와있으니 확인해보자.

### BNL 이란?

MySQL이 BNL을 제공하는 이유는 NL 조인만 지원하는 한계점을 보완하기 위해서이다. 예를 들어, 조인 칼럼 인덱스가 없다고 가정해보자. 이경우 다른 DBMS는 해시 조인 혹은 머지 조인을 사용한다. 그런데 NL 조인만 지원하는 MySQL은 이 문제를 어떻게 처리할까? 

만일 BNL 방식이 없다면, Driving 테이블의 건수만큼 Inner 테이블을 스캔 (또는 Index Full Scan)해야만 한다. 이것은 어마어마한 성능 저하를 초래한다. 이 문제를 어느 정도 완화하기 위해서 MySQL은 BNL 방식을 고안한다.

BNL 방식은 프로세스 내에 별도의 버퍼 (이를 조인 버퍼라고 합니다)에 Driving 테이블의 레코드를 저장한 후에 Inner 테이블을 스캔하면서 조인 버퍼를 탐색하는 방식이다. 따라서 BNL 방식을 사용하면 BNL 방식을 사용하지 않는 것에 비해서는 빠르다. 하지만 BNL 방식은 Nested Loop 조인의 한계를 개선하기 위한 차선책일 뿐 근본적인 해결책은 아니다. Sort Merge 조인이나 Hash 조인에 비해서 턱없이 느린 방식이기 때문이다.
