### ISSUE TITLE
[5-5장] 최신 MySQL에서는 거리를 비교하는 Distance() 함수를 지원하는가.

### ISSUE THREAD

**Issue by toneyparky** [gazi-gazi/real-mysql#31]
> `p.240` R-Tree는 도형간의 포함 관계를 이용해 만들어진 인덱스다 따라서 Contains나 intersect등과 같은 포함 관계를 비교하는 함수로 검색을 수행하는 경우에만 인덱스를 이용할 수 있다. 대표적으로는 현재 사용자의 위치로부터 반경 5km이내의 음식점 검색 등과 같은 검색에 사용가능하다. **현재 출시되는 버전의 MySQL에서는 거리를 비교하는 Distance() 함수를 지원하지 않으므로 Contains()나 Intersect()를 이용해 거리 기반의 비교를 사용한다.**

질문 : 
1. `MySQL 8` 버전대 혹은 그 이후의 최신 버전에서는 거리를 비교할 때에 `Distance() `함수를 지원하는지 궁금합니다. 
2. 지원한다면 어떤 방식으로 구현되어있는지도 궁금합니다. (지원하지 않지만 구현할 경우에 대해서는 8장에 나온다네요)

**Comment by giantim** [comment]
[MySQL 8 버전대 부터는 Distance 함수를 지원합니다.](https://dev.mysql.com/doc/refman/8.0/en/spatial-relation-functions-object-shapes.html)

- ST_Distance(g1, g2 [, unit])

```sql
mysql> SET @g1 = ST_GeomFromText('POINT(1 1)');
mysql> SET @g2 = ST_GeomFromText('POINT(2 2)');
mysql> SELECT ST_Distance(@g1, @g2);
+-----------------------+
| ST_Distance(@g1, @g2) |
+-----------------------+
|    1.4142135623730951 |
+-----------------------+

mysql> SET @g1 = ST_GeomFromText('POINT(1 1)', 4326);
mysql> SET @g2 = ST_GeomFromText('POINT(2 2)', 4326);
mysql> SELECT ST_Distance(@g1, @g2);
+-----------------------+
| ST_Distance(@g1, @g2) |
+-----------------------+
|     156874.3859490455 |
+-----------------------+
mysql> SELECT ST_Distance(@g1, @g2, 'metre');
+--------------------------------+
| ST_Distance(@g1, @g2, 'metre') |
+--------------------------------+
|              156874.3859490455 |
+--------------------------------+
mysql> SELECT ST_Distance(@g1, @g2, 'foot');
+-------------------------------+
| ST_Distance(@g1, @g2, 'foot') |
+-------------------------------+
|             514679.7439273146 |
+-------------------------------+
```

쿼리의 형식과 예시는 위와 같습니다. 입력 인수 g1, g2는 Spatial Type의 데이터 값을 입력합니다. unit에는 세계 지구 좌표 시스템(WGS84)의 좌표계 범위나 도량형 값(meter, foot 등)을 입력해 단위를 변환합니다. 거리는 입력한 좌표의 직선 거리를 계산합니다. 
WGS84의 좌표 범위 확인은 [이 문서](https://spatialreference.org/ref/epsg/4326/)를 확인해 주세요.

과거 버전에서 거리를 계산하던 방법에 대해서는 [이 문서](https://medium.com/maatwebsite/the-best-way-to-locate-in-mysql-8-e47a59892443)를 참고해 주세요 :)
