### ISSUE TITLE
[5-6장] Fractal-Tree를 사용하는 다른 DBMS가 있는지 여부와 TokuDB의 동시성 성능 개선 여부

### ISSUE THREAD

**Issue by toneyparky** [gazi-gazi/real-mysql#32]
> `p.244` **TokuDB는 동시성이 떨어지기에** 웹 서비스 같은 OLTP 환경에는 아직 적용하기 무리가 있다. 하지만 OLAP나 DW 와 같은 대용량 분석 시스템에는 상당히 적합할 것으로 보인다. 또한 **Fractal-Tree가 적용된 DBMS는 MySQL의 TokuDB가 유일하므로 Fractal-tree를 사용하려면 TokuDB 스토리지 엔진으로 테이블을 생성하는 방법 밖에 없다.**

질문 :
1. 책이 나온지 조금 오래 되었기에 이후에 `Fractal-Tree`의 저작권 문제가 해결되어, 혹은 저작권을 보유하는 `TokuTek`에서 다른 `DBMS`를 위한 스토리지 엔진을 만들었는지 궁금합니다. 
2. `TokuTek`에서 제작한 `TokuDB`의 동시성 성능이 개선되어 `OLTP` 환경에 적용해서도 무리 없이 사용될 수 있는지, 아니면 그렇지 않고 지금까지고 `OLAP`나  `DW`에 특화되어 사용되는지 궁금합니다. 

추가적으로 `Fractal-Tree`의 동시성이 안좋은 이유는 책 `p.241` 아랫부분부터 `p.242` 윗부분에 나오듯 인덱스 키가 추가, 삭제 될 때에 `B-Tree` 인덱스보다 더 많은 정렬 작업이 필요해서일까 싶네요.

**Comment by giantim** [comment]
2013년 쯤 저작권을 오픈소스화 했다고 합니다. 관계형 데이터베이스인 MySQL과 MariaDB 뿐만 아니라 NoSQL 스토리지 엔진([TokuMX](https://en.wikipedia.org/wiki/TokuMX)) 역시 만들었는데 해당 정보는 [Tokutek 깃헙](https://github.com/Tokutek?q=&type=&language=)에서 확인해 볼 수 있습니다.

동시성에 관한 이슈 역시 개선되어 OLTP 환경에서도 사용해도 된다 라는 [실험 결과를 공개](https://minervadb.com/index.php/2018/08/06/comparing-tokudb-rocksdb-and-innodb-performance-on-intelr-xeonr-gold-6140-cpu/)했습니다.

Fractal-Tree의 동시성이 안좋았던 이유는 추측한대로 인덱스 키가 추가, 삭제될 때 데이터에 대한 잠금 + 인덱스보다 더 많은 정렬 작업이 수행되어야 하니 과거에는 성능이 안좋았던 것 같네요 :)

**Comment by jjj0611** [comment]
> Fractal-Tree의 동시성이 안좋았던 이유는 추측한대로 인덱스 키가 추가, 삭제될 때 데이터에 대한 잠금 + 인덱스보다 더 많은 정렬 작업이 수행되어야 하니 과거에는 성능이 안좋았던 것 같네요 :)

엇 이 문제를 어떻게 해결했을까요? 

`p.243`을 보면 Fractal-Tree의 평균적인 능력이 B-Tree보다 400배 가량 빠르고 실제로 TokuDB의 키 추가 및 삭제 작업이 InnoDB보다 약 100배 가량 빠른 처리 속도를 보여준다고 했는데, 단일 스레드에서 성능이 좋지만, 잠금이 일어나기 때문에 혹은 더 많은 정렬 작업이 수행되어야 하기 때문에 멀티 스레드 환경에서는 성능이 더 안 좋을 수 있다는건데, 이 문제(잠금 + 많은 정렬 작업)를 해결한 방법이 궁금하네요 :)

**Comment by giantim** [comment]
[Concurrency Improvements in TokuDB v6.6 (Part 2)](https://www.percona.com/blog/2013/02/05/concurrency-improvements-in-tokudb-v6-6-part-2/)를 읽고 이해한 내용을 바탕으로 설명하겠습니다. 잘못된 내용이 있으면 지적해주세요 :)

읽기 동시성과 쓰기 동시성에 대해 나눠서 설명했습니다. 먼저 Fractal Tree의 구조를 알아야 하니 #34 이슈를 먼저 읽어주세요 :)

읽기 동시성의 경우 동일하지 않은 리프 노드에 있는 데이터를 읽을 때 쓰레드들은 최하위 리프 노드에 대한 독점 접근 권한만 얻으면 된다고 합니다. 그 상위의 공통 브랜치 노드의 경우에는 공통 접근 제어권을 가질 수 있어서 동시성 문제를 해결한다고 합니다.

쓰기 동시성의 경우 메시지를 루트 노드의 메시지 버퍼에 보내는 것이 아닌 몇 단계의 플러시 과정을 미리 거쳐서 하위 브랜치 노드의 메시지 버퍼에서부터 출발하도록 진행시킨다고 합니다. 제가 이해한 바로는 이런 방식으로 메시지를 수행한다면 만약 브랜치 노드의 출발점이 다를 때 다루는 하위 노드들이 쓰레드마다 다르게 되므로 동시성 문제를 해결할 수 있는 것으로 이해했습니다.
