### ISSUE TITLE
[5.5.2장] R-Tree에서 Contains 또는 Intersect 함수 사용

### ISSUE THREAD

**Issue by jjj0611** [gazi-gazi/real-mysql#33]
> `p.240` 여기서 Contains()나 Intersect() 연산은 사각형 박스와 같은 다각형(Polygon)으로만 연산할 수 있으므로...

요청 : Contains 예시를 보면 Contains(px, 사각상자) 이렇게 나오는데  `사각상자`에 어떤 방식으로 데이터가 들어가서 다각형을 다 지원할 수 있는지 궁금해요~ Contains를 직접 사용하는걸 보면 좋을 것 같아요~

**Comment by giantim** [comment]
예제는 MySQL 5.7로 진행합니다 :)

[MySQL 5.7에서 지원하는 공간 데이터 타입](https://dev.mysql.com/doc/refman/5.7/en/gis-geometry-class-hierarchy.html)에 대해 점과 다각형을 지원하도록 최상위 GEOMETRY 객체를 이용해 테이블을 만들어 보겠습니다.
```sql
create table tb_location (
    id BIGINT NOT NULL AUTO_INCREMENT,
    geo GEOMETRY NOT NULL,
    PRIMARY KEY (id),
    SPATIAL KEY sx_geo (geo)
) ENGINE=INNODB;
```
아래 그림과 같이 예시 데이터를 만들어 보겠습니다.
<img src="https://user-images.githubusercontent.com/39546083/102708370-05abf980-42e6-11eb-8fab-1511f8a20c89.png" width="500">
```sql
insert into tb_location (geo) values(point(4, 5)); -- // 점
insert into tb_location (geo) values(ST_GeomFromText('Polygon((6 5,
                                                            13 5,
                                                            6 12,
                                                            6 5))')); -- // 직각삼각형
insert into tb_location (geo) values(ST_GeomFromText('Polygon((10 12,
                                                                13 12,
                                                                10 14,
                                                                13 14,
                                                                11 15,
                                                                10 12))')); -- // 오각형
```
문자열을 좌표계로 바꾸는 MySQL의 함수는 [여기](https://dev.mysql.com/doc/refman/5.7/en/gis-wkt-functions.html#function_st-geomfromtext)를 참고해주세요. 다각형을 정의할 때 가장 처음에 입력하는 좌표(출발 좌표)와 가장 마지막에 입력하는 좌표(도착 좌표)가 동일해야 다각형을 그릴 수 있습니다.

좌표를 검색할 때 조건절(where)에 입력하는 MBR의 경우 쿼리를 작성하는 개발자가 직접 정의해서 입력해 주어야 합니다.
3개의 도형을 모두 포함하는 경우, 삼각형과 오각형의 일부만 포함하는 경우의 쿼리를 작성해서 어떻게 결과가 나오는지 살펴보겠습니다.

### 1. 3개의 도형을 모두 포함하는 경우
<img src="https://user-images.githubusercontent.com/39546083/102709005-ec0cb100-42e9-11eb-8f50-9c79845fde0c.png" width="500">

```sql
SELECT id, ST_AsText(geo)
FROM tb_location
WHERE MBRContains(
    ST_GeomFromText('POLYGON((3 4,
                              15 4,
                              15 16,
                              3 16,
                              3 4))'),
    geo
  );
```

결과는 아래와 같이 저장한 모든 좌표가 출력됩니다.
![image](https://user-images.githubusercontent.com/39546083/102709028-1bbbb900-42ea-11eb-9b56-1ed9ddba5a73.png)
실행계획을 보면 인덱스를 정상적으로 잘 이용했습니다.
![image](https://user-images.githubusercontent.com/39546083/102709058-4e65b180-42ea-11eb-8131-62d6d060028b.png)

### 2. 삼각형과 오각형의 일부만 포함하는 경우
<img src="https://user-images.githubusercontent.com/39546083/102709138-d51a8e80-42ea-11eb-90cb-e9a63a41ad08.png" width="500">

```sql
SELECT id, ST_AsText(geo)
FROM tb_location
WHERE MBRContains(
 ST_GeomFromText('POLYGON((5 9,
                              14 9,
                              14 13,
                              5 13,
                              5 9))'),
    geo
  );
```

결과는 도형 객체의 일부만 포함 시 해당 객체를 결과로 출력하지 않습니다.
![image](https://user-images.githubusercontent.com/39546083/102709151-fd09f200-42ea-11eb-8bcb-c9112cb03e31.png)
실행계획을 보면 인덱스를 정상적으로 잘 이용했습니다.
![image](https://user-images.githubusercontent.com/39546083/102709153-098e4a80-42eb-11eb-99ba-c651f4f57aa7.png)

예시에서 사용한 MBRContains() 함수는 책에서 소개한 구버전 함수가 deprecated 되어 대체된 함수입니다. 해당 내용은 [여기](https://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-mbr.html#function_contains)에서 확인하시면 됩니다.

질문주신 내용중에 사각상자에 어떻게 데이터가 들어가서 다각형을 다 지원하는지 궁금하다고 하셨는데 다각형의 경우는 MySQL에서 지원하는 데이터 타입이고 조건절(where)에 정의하는 사각상자의 경우 검색을 수행할 범위를 지정한다라고 생각하시면 될 것 같네요 :)

**Comment by jjj0611** [comment]
```sql
ST_GeomFromText('Polygon((6 5,
                                  13 5,
                                  13 12,
                                  6 12,
                                  6 5))')
```
이렇게 사각상자를 넣어줄 수 있다는 말이군요?
답변 감사해요~~~

**Comment by toneyparky** [comment]
지도와 관련한 지식이 차곡차곡 쌓이네요~👏👏👏👏👏
