### ISSUE TITLE
[5.7장] 전문검색(Full Text Search) 인덱스를 많이 사용하는가?

### ISSUE THREAD

**Issue by jjj0611** [gazi-gazi/real-mysql#35]
질문: 전문검색 인덱스를 읽으면 사실상 구분자는 거의 사용하지 않을거 같고 n-gram 방식만 사용할 것으로 보여요. 근데 여기서 중요한 것은 최소글자 수인 것 같아요. 인덱싱할 최소글자 수를 줄이게 되면 인덱싱되는 데이터가 많아져서 인덱스의 크기가 커질 것 같고, 최수글자 수가 커지면 원하지 않는 데이터 셋이 나올 수도 있을거 같아요. 보통 어떤 방식으로 사용할까요?

질문 2: 요새에도 이 전문검색 인덱스를 많이 사용하는지 궁금하네요. 이 글을 읽으면서 elastic search가 많이 떠올랐는데, 실제로 MySQL의 전문검색 인덱스를 걸어서 사용하는 경우가 많이 있는지, 그리고 가능하다면 elastic search는 어떤 방식(알고리즘)으로 인덱싱 하기에 검색을 구현할 때 많이 사용하는지 궁금하네요 :)

**Comment by giantim** [comment]
### 질문 1
이 질문에 대해서는 정확한 답변을 못 드리겠네요. 전문 검색 인덱스와 n-gram 인덱싱에 대해서 검색을 해봤는데 이 기술을 적용한 어떤 도메인에 대한 베스트 프랙티스가 나오기 보다는 어떤 방식으로 사용하는지에 대한 글들밖에 찾지 못했습니다. 검색을 통해서 알게된 몇가지 정보에 대해서만 간략하게 정리해 드릴께요 :)

전문 검색 인덱스를 적용하는 경우는 ```LIKE 구문을 통해서 검색하는 것 보다 성능을 높이기 위해서``` 라고 합니다. WHERE절에 LIKE를 이용해 문자열을 검색하면 해당 문자가 포함되는 것이 있는지 풀 테이블 스캔을 하기 때문에 이런 비용을 낮추기 위해 인덱스를 만들어서 검색을 수행한다고 합니다.
사용법에 관한 예제는 [이 문서](https://www.digitalocean.com/community/tutorials/how-to-improve-database-searches-with-full-text-search-in-mysql-5-6-on-ubuntu-16-04)를 참고해주세요 :)

n-gram 방식의 문자열 인덱스의 경우 장점은 ```조사(은/는, 이/가)```를 지원할 수 있다는 것입니다. 영어, 라틴어 같은 서구권의 언어는 조사가 없이 단어들을 띄어쓰기로만 구분하는데 중국어, 일본어, 한국어(CJK)의 경우 단어+단어를 결합하여 새로운 문자를 만들 수 있기 때문에 이런 언어들의 경우 n-gram을 적용하면 더 높은 검색 정확도를 얻을 수 있다고 합니다. 
n-gram 방식의 경우 MySQL 5.7부터 InnoDB의 내장 인덱스 엔진으로 포함되었기 때문에 선언 해주면 간단하게 적용할 수 있습니다. 테이블을 생성할 때 적용하는 구문은 아래와 같습니다.
```sql
CREATE TABLE articles (
        id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
        title VARCHAR(100),
        FULLTEXT INDEX ngram_idx(title) WITH PARSER ngram
) Engine=InnoDB;
```
인덱스를 선언할 때 ```WITH PARSER ngram``` 으로 명시적으로 어떤 방식으로 파서를 정의할지 선언해주면 됩니다.
n-gram 방식의 인덱스의 경우 책에서 소개한 것 처럼 프론트 인덱스와 백엔드 인덱스를 만들기 때문에 크기가 증가한다는 문제가 있습니다. 그리고 질문에 남겨주신 것과 같이 하나의 n-gram으로만 인덱스를 만들었을 때 원하지 않는 데이터 셋의 생성으로 검색 결과가 부정확해진다는 문제도 있습니다. 검색 결과의 정확성을 높이기 위해서 Multi-gram Index를 지원한다고 합니다. 예를 들어 2글자씩 나누기, 3글자씩 나누기를 해서 여러 개의 글자수로 인덱스를 생성하는 것입니다. 이것 또한 문제가 발생합니다. 검색 효율은 증가하지만(일반적인 경우에는 비슷한 검색 효율을 보장하고 엣지 케이스에 대한 검색 효율성이 증가한다고 합니다) 인덱스의 사이즈가 커집니다.
그리고 다양한 버그 관련 문서를 여러 글에서 소개하고 있어서 과연 실제로 많이 사용될지는 아직 잘 모르겠습니다.

버그 관련 문서
- [Fulltext search can not find word which contains "," or "."](https://bugs.mysql.com/bug.php?id=85876)
- [Stopword handling for ngram parser prevent searching meaningful words.](https://bugs.mysql.com/bug.php?id=85875)
- [Fulltext query is too slow when each ngram token match a lot of documents.](https://bugs.mysql.com/bug.php?id=85880)

참고
- [nGram full text search (by 이성욱)](https://www.slideshare.net/IGooLee/ngram-full-text-search-by)
- [12.10.8 ngram Full-Text Parser](https://dev.mysql.com/doc/refman/5.7/en/fulltext-search-ngram.html)
- [InnoDB 전문 검색 : N-gram Parser](https://mysqlserverteam.com/innodb-%EC%A0%84%EB%AC%B8-%EA%B2%80%EC%83%89-n-gram-parser/)

여기까지가 제가 정리한 내용인데 도움이 되었으면 좋겠네요 :)

### 질문2
도메인의 규모와 목적에 따라서 나눠지지 않을까 생각합니다. MySQL을 사용한다면 하나의 서비스나 시스템에 대해 데이터 저장, 관리, 저장된 데이터 내에서의 간단한 검색 기능을 제공할 때 사용하고 ES의 경우 저장된 어떤 데이터에 대해 특정한 목적을 갖고 검색 기능이 필요할 때 적용하면 되지 않을까요?
제가 참고했던 문서들 입니다. 한번 읽어 보시면 좋을 것 같아요!
- [Elastic search full text vs mysql full text?](https://stackoverflow.com/questions/41892179/elastic-search-full-text-vs-mysql-full-text)
- [MySQL, Full Text Search (전문검색, FTS)](https://grip.news/archives/1538)

ES의 검색 알고리즘의 경우 4단계의 인덱싱 과정을 거친 결과를 이용해 유사도를 판별한다고 이해했습니다.
잘 정리해놓은 글이 있어서 참고하시면 좋을 것 같네요 :)
- [Elasticsearch는 검색을 어떻게 하는가?](https://lazy-programmer.tistory.com/entry/Elasticsearch%EB%8A%94-%EA%B2%80%EC%83%89%EC%9D%84-%EC%96%B4%EB%96%BB%EA%B2%8C-%ED%95%98%EB%8A%94%EA%B0%80)
- [[엘라스틱서치] Elasticsearch in action 정리(4) - 유사도 검색](https://12bme.tistory.com/479)

**Comment by jjj0611** [comment]
n-gram 관련 참고 문서 3번째(InnoDB 전문 검색 : N-gram Parser)를 보면 일반적으론 2를 사용한다네요 :)
multi-gram index의 경우는 min과 max token 사이즈를 줘서 사용을 하나보네요!

n-gram  방식에서 조사를 지원한다는게 언어에 따라서 지원을 해주게 되는건가요?
조사 같은 문제로 n-gram의 정확도가 떨어질 것 같다는 생각을 했는데 지원해주는 방식이 있나보네요.
혹시 이것과 관련한 것을 참고 문서에서 찾지 못했는데 혹시 어디서 찾았는지 공유 가능할까요~??

**Comment by giantim** [comment]
[이분](https://gywn.net/2017/06/mysql_57-ngram-ft-bug-and-learn/)이 테스트 하셨는데 초기에 성능 문제가 있었다고 하네요!

**Comment by toneyparky** [comment]
Elastic Search는 공부하고 있는 유안의 첨언이 있다면 좋겠네요~
