### ISSUE TITLE
[5.8장] 다른 DBMS에서의 함수기반 인덱스 

### ISSUE THREAD

**Issue by jjj0611** [gazi-gazi/real-mysql#36]
> `p.250` 테이블에 함수의 결과 값을 저장하기 위한 칼럼을 추가하고, 그 칼럼에 인덱스를 생성해서 사용하면 된다. 조금은 불편하겠지만 다른 DBMS의 함수 기반 인덱스와 같은 효과를 얻을 수 있다.

질문 : MySQL에서는 그냥 함수를 저장할 칼럼을 추가하고 그 칼럼에 인덱스를 생성한다(함수를 통해 값이 저장되든 아니든 그냥 인덱스가 걸리는거겠지?). 근데 다른 DBMS에서는 함수기반 인덱스를 조금 더 편하게 사용하는 것과 같이 이야기 하는데, 다른 DBMS에서는 함수 기반 인덱스가 어떻게 작동할까요?

질문 2: 위 장과 같이 다뤄지는 비트맵 인덱스에 대해서도 이야기 해보면 좋을 것 같아요 :)

**Comment by giantim** [comment]
### 질문 1
[MySQL 8.0 부터 함수 기반 인덱스를 지원하네요!](https://dev.mysql.com/doc/refman/8.0/en/create-index.html#create-index-functional-key-parts)
간단한 예시에 대해서는 [여기](http://minsql.com/mysql8/B-3-C-functionBasedIndex/)를 참고해주세요.

그럼 저희가 사용하는 MySQL 5.7에서는 어떤 방식으로 함수 기반 인덱스를 지원할까요? [Virtual Columns in MySQL and Use cases.](https://mydbops.wordpress.com/2017/07/19/virtual-columns-in-mysql-and-use-cases/)를 읽고 정리한 내용입니다 :)

MySQL 5.7은 ```virtual column```을 이용해서 함수 기반 인덱스를 지원하고 있습니다. 
virtual column의 기능은 아래와 같습니다.
- virtual column은 테이블의 결과로 표시되지만 디스크에 저장되지 않는다.
- virtual column은 MySQL 5.7의 상위 기능 중 하나이며, 동일한 테이블에 있는 하나 이상의 다른 필드에서 파생된 값을 새 필드에 저장할 수 있다.

아래와 같이 생성할 수 있습니다.
```sql
create table mydbops_lab_test (
    id int(11) NOT NULL AUTO_INCREMENT primary key,
    firstname varchar(20),
    lastname varchar(20),
    full_name char(41) GENERATED ALWAYS AS (concat(firstname,' ',lastname)),
    email_id varchar(25)
)ENGINE=INNODB;
```
virtual column으로 지정할 컬럼에 ```GENERATED ALWAYS AS를 선언```하고 ```괄호 안에 함수를 정의```하면 됩니다.
테이블 정의 결과는 아래와 같습니다.
![image](https://user-images.githubusercontent.com/39546083/102743303-904e3080-439a-11eb-80f9-4f8021ecdf37.png)

데이터를 집어넣고 결과를 확인해보겠습니다.
```sql
insert into mydbops_lab_test (firstname, lastname, email_id) values
('john', 'rubin', 'rubin@gmail.com'),
('mark', 'henry', 'mark@gmail.com'),
('peter', 'parker', 'peter@yahoo.com'),
('jim', 'rose', 'jim@outlook.com');

select * from mydbops_lab_test;
```
![image](https://user-images.githubusercontent.com/39546083/102743532-fc309900-439a-11eb-89ee-1dbf0b0064a4.png)
값을 넣지 않은 fullname 컬럼에 대해서 firstname + lastname으로 지정한 함수 결과대로 테이블에 출력이 되었습니다.


다음으로 virtual column에 인덱스를 지정해 보겠습니다. virtual column에 지정하는 인덱스에는 아래와 같은 특징이 있습니다.
- MySQL InnoDB에서는 가상 열의 보조 인덱스를 지원합니다. 다른 형식 인덱스는 지원되지 않습니다(전문 검색 인덱스/공간 좌표 인덱스).
- 보조 인덱스는 하나 이상의 virtual column 또는 virtual column과 일반 column 또는 저장된 생성된 열의 조합에 생성할 수 있습니다. virtual column을 포함하는 보조 인덱스는 고유하게 정의될 수 있습니다.

예제 테이블은 아래와 같습니다.
```sql
create table mydbops_lab_test_1 (
    id int(11) NOT NULL AUTO_INCREMENT primary key,
    Total_cost float(9,4),
    Expensive float(9,4),
    Balance_amount float(12,6) GENERATED ALWAYS AS (Total_cost - Expensive),
    email_id varchar(25),
    name varchar(30)
)ENGINE=INNODB;

DESC mydbops_lab_test_1;
```
![image](https://user-images.githubusercontent.com/39546083/102743944-e7a0d080-439b-11eb-97bf-2f296a3a5f3c.png)

위와 같은 테이블을 만든 후 인덱스를 추가하고 실행 계획을 살펴보겠습니다.
```sql
alter table mydbops_lab_test_1 add index idx_Balance_amount(Balance_amount);

explain 
select id,name,Total_cost,Balance_amount 
from mydbops_lab_test_1 
where Balance_amount < 2000 
order by Balance_amount desc;
```
![image](https://user-images.githubusercontent.com/39546083/102744163-80375080-439c-11eb-88c8-67aa1289e741.png)
정상적으로 virtual column에 대한 인덱스를 이용하는 것을 확인할 수 있습니다.

문서에서 설명한 virtual column의 인덱스의 장점과 단점은 아래와 같습니다.

장점
- virtual column은 쿼리를 단순화하고 통합하는 방법으로 사용할 수 있습니다.
- 복잡한 조건을 생성된 열로 정의하고 테이블의 여러 조회에서 참조하여 모든 조건이 정확히 동일한지 확인할 수 있습니다.
- JSON 열과 같이 직접 인덱싱할 수 없는 유형의 열 작업에 유용합니다.
- [NOT NULL] 열은 MySQL 5.7에서만 허용되지만 MariaDB에서는 지원되지 않습니다.

단점
- virtual column의 단점은 생성된 열(virtual column에 이용하는 컬럼)의 값으로 한 번, 인덱스에 한 번, 두 번 값이 저장된다는 것입니다.
- 생성된 열이 인덱싱된 경우 최적화 도구는 열 정의와 일치하는 쿼리 식을 인식하고 쿼리 실행 중에 해당 열의 인덱스를 사용합니다. -> 인덱스의 유연성이 떨어진다는 뜻? 인덱스의 유연성이란 하나의 인덱스로 여러 엑세스 유형을 수용할 수 있는가이다.

### 질문 2
아직까지 MySQL에서는 비트맵 인덱스를 지원하지 않네요 :)
비트맵 인덱스는 DSS(Decision Support System - 의사 결정 지원 시스템)에 적합한 인덱스라고 합니다. 이 시스템의 특징은 커다란 데이터 집합에 대해 오래 지속되는 쿼리에 특화된다고 합니다. OLTP는 실시간성을 중요하게 여기지만 DSS에서 사용자는 수분, 수시간, 수일이 걸리는 쿼리가 완료되기를 기대한다고 합니다.

참고
- [비트맵 인덱스란](http://www.gurubee.net/lecture/1109)
- [2.2. 비트맵(Bitmap) 인덱스](http://wiki.gurubee.net/pages/viewpage.action?pageId=1507452)
- [비트맵 인덱스의 변경과 생성](http://www.gurubee.net/lecture/2958)

**Comment by jjj0611** [comment]
오 8.0부터 지원하네요 :)
좋은 자료 감사합니다~!
