### ISSUE TITLE
[5.9.2장] 클러스터 키 값의 변경과 레코드의 변경

### ISSUE THREAD

**Issue by jjj0611** [gazi-gazi/real-mysql#37]
> `p.253~254` 그렇다면 InnoDB 테이블에서 보조 인덱스가 실제 레코드가 저장된 주소를 가지고 있다면 어떻게 될까? 클러스터 키 값이 변경될 때마다 데이터 레코드의 주소가 변경되고 그때마다 해당 테이블의 모든 인덱스에 저장된 주소 값을 변경해야 할 것이다.

질문 : 실제 레코드 주소가 저장된 주소를 가지고 있지 않고 클러스터 키 값(프라이머리 키)을 가지고 있다고 하더라도 변경해야하는건 동일하지 않나요?
`인덱스 - 저장된 주소`라면 클러스터 키 값이 변경되면(레코드 주소가 변경되기 때문에) 저장된 주소를 바꿔줘야 한다.
`인덱스 - 클러스터 키 값`이라면 클러스터 키 값이 변경되면(클러스터 키 값 자체가 변경됐기 때문에) 보조 인덱스의 값(클러스터 키 값)이 바뀐 것이므로 보조 인덱스의 값을 변경해야하는건 동일하지 않나요?

**Comment by jnsorn** [comment]
### 수정중입니다

오 그렇게 생각할수도 있네요! 저도 궁금해져서 관련해서 좀 찾아봤는데, 명확한 답을 찾지는 못했어요. 그래도 찾은 내용을 공유해보도록 할게요.

우선 [MySQL docs](https://dev.mysql.com/doc/refman/8.0/en/innodb-index-types.html)를 먼저 찾아봤는데, Real MySQL 책과 비슷한 내용만 있더라고요. 

> **How Secondary Indexes Relate to the Clustered Index**
All indexes other than the clustered index are known as secondary indexes. In InnoDB, each record in a secondary index contains the primary key columns for the row, as well as the columns specified for the secondary index. InnoDB uses this primary key value to search for the row in the clustered index.

그래서 더 찾아보니 `이것이 MySQL이다`라는 책에서는 보조인덱스의 칼럼 값으로 실제 데이터가 저장된 위치의 고유값(`페이지번호#오프셋`)이 저장된다고 합니다. ([영상](https://www.youtube.com/watch?v=qW9X4w_SnT4),[글1](https://m.blog.naver.com/PostView.nhn?blogId=thwlstmxk&logNo=221062514161&proxyReferer=https:%2F%2Fwww.google.com%2F), [글2](https://nangkyeong.tistory.com/entry/%EC%9D%B4%EA%B2%83%EC%9D%B4-MySQL%EC%9D%B4%EB%8B%A4%EB%A1%9C-%EC%A0%95%EB%A6%AC%ED%95%B4%EB%B3%B4%EB%8A%94-%EC%9D%B8%EB%8D%B1%EC%8A%A4-%EA%B0%9C%EB%85%90))

![image](https://user-images.githubusercontent.com/31095063/102732823-0b095280-437f-11eb-84e6-7e6eac6eb14a.png)

이 내용에 의하면, 클러스터 키 값을 변경해도 페이지와 오프셋으로 기록되기 때문에 전체가 일괄적으로 변경되는 게 아닌 변경이 일어난 페이지에 속한 칼럼에 대해서만 값 변경이 일어남을 확인할 수 있습니다.

**Comment by jnsorn** [comment]
좋은 질문이네요!

우선 보조 인덱스의 값은 클러스터링 인덱스의 존재 여부에 따라 칼럼 값이 다르게 저장됩니다.

## 클러스터링 인덱스 존재하지 않을 경우
보조 인덱스의 컬럼 값은 `데이터페이지의 번호#오프셋`이 됩니다.

<img width="547" alt="스크린샷 2020-12-21 오전 11 24 05" src="https://user-images.githubusercontent.com/31095063/102764477-8a6a4680-43be-11eb-9562-665f7edb3667.png">

## 클러스터링 인덱스 존재할 경우
보조 인덱스의 컬럼 값은 `클러스터 키`가 됩니다.

![image](https://user-images.githubusercontent.com/31095063/102764319-5131d680-43be-11eb-9dbb-12c222c1516f.png)

왜 이렇게 구성했을까요? 그림을 보기에도 직접 주소(페이지번호#오프셋)을 갖고 있는 게 검색이 더 빠르고 효율적일 것 같은데 말이죠 🤔

실제로 검색은 주소를 갖고 있는 경우가 조금 더 빠르지만 데이터를 변경(추가, 수정, 삭제)시  전체 보조 인덱스를 뒤엎어야 하기 때문에 큰 문제가 발생하게 됩니다. 아래서 조금 더 구체적으로 말씀드릴게요.

## 검색
김경호의 주소를 검색해 봅니다.

### 보조 인덱스의 칼럼 값이 주소를 가질 경우(가정)
김경호 -> 페이지 100 -> 100페이지에 가서 주소 -> 주소에서 데이터를 읽음(전남)
3번째 페이지만에 값을 읽을 수 있습니다.

### 보조 인덱스의 칼럼 값이 클러스터 키를 가질 경우
김경호 -> 페이지 100 -> 100페이지가서 KKH-> KBS 1001페이지 이동 -> 주소에서 데이터를 읽음(전남)
4번째 페이지만에 값을 수 있습니다.

검색은 주소 값을 가지고 있는 게 유리해보이네요.

### 추가,삭제,변경
`MMI 멍멍이 서울` 값이 추가합니다.

### 보조 인덱스의 칼럼 값이 주소를 가질 경우(가정)
![image](https://user-images.githubusercontent.com/31095063/102767139-788aa280-43c2-11eb-8a79-2b227f8fbdd7.png)

_마땅한 자료가 없어 위의 사진을 가지고 흐름을 적어보았는데요, 클러스터링 인덱스가 존재하기 때문에 아래 데이터들은 다 이니셜 순으로 정렬이 되어있는 상태라고 가정하고 봐주세요._

1. 1001번 페이지에 MMI 멍멍이를 추가하려고 하지만 페이지가 가득 차 페이지 분할이 일어납니다. (아래 사진을 봐주세요)
2. 페이지 분할이 일어나면서 기존의 데이터들과 그 이후 페이지들 주소가 다 변경됩니다.
3. 이 변경은 데이터 페이지에서만 그치는 것이 아닌 보조 인덱스의 리프 페이지에서도 변경을 일으키게 됩니다.

### 보조 인덱스의 칼럼 값이 클러스터 키를 가질 경우
![image](https://user-images.githubusercontent.com/31095063/102767114-73c5ee80-43c2-11eb-9d94-760889ae5fce.png)

1. 위의 1번과 똑같이 페이지 분할이 일어납니다.
2. 페이지 분할이 일어나면서 기존의 데이터들과 그 이후 페이지들 주소가 다 변경됩니다.
3. 하지만 보조 인덱스는 클러스터 키값으로 저장되어 있기 때문에 딱히 변경해주지 않아도 됩니다. 

(변경 역시 마찬가지로 보조 인덱스의 칼럼값은 바뀌겠지만, 다른 레코드에 영향을 미치진 않습니다.)

## 결론

보조 인덱스의 칼럼 값을 클러스터 키값으로 갖게 되면 검색이 조금 덜 빠르지만, 추가수정삭제 때문에 매번 변경이 일어나는 걸 방지할 수 있습니다.
여기서 검색이 조금 더 빠른 것은 아주 미세한 차이며, 보조 인덱스의 칼럼 값들이 변경 일어나는 상황이 더 시스템에 부하를 주기 때문에 보조 인덱스의 칼럼 키값을 클러스터 키값으로 구성하게 되었습니다.





---
출처: 이것이 MySQL이다 [영상](https://www.youtube.com/watch?v=pOaLJVnGJgM&t=4s)
