### ISSUE TITLE
[5.11.1장] 자식 테이블의 변경이 대기하는 경우

### ISSUE THREAD

**Issue by jjj0611** [gazi-gazi/real-mysql#39]
> `p.259` 표 부분!

질문 : 커넥션 -1에서 현재는 UPDATE를 치고 있지만, 이게 DELETE 쿼리면 어떻게 될까요?
`DELETE tb_parent WHERE id=2;`를 하고, 5번에서 ROLLBACK이 아니라 COMMIT을 찍으면
4번에서 `UPDATE tb_childe SET pid=2 WHERE id=100;`에서 fk에 해당하는 record가 존재하지 않다고 예외가 발생할까요?
아니면 변경이 되고(pid=2로 바뀌고) CASCADE ON DELETE에 의해 해당 레코드가 삭제될까요?
아마 전자일 것 같은데, 테스트 해보면 재밌을 것 같아요 :)

**Comment by giantim** [comment]
작업번호 2번의 쿼리를 DELETE로 변경하고 작업번호 5번을 ROLLBACK이 아닌 COMMIT으로 데이터를 삭제했을 때 작업번호 4번이 어떤 동작을 하는지 살펴보겠습니다 :)
```sql
CREATE TABLE tb_parent (
    id INT NOT NULL,
    fd VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=INNODB;

CREATE TABLE tb_child (
    id INT NOT NULL,
    pid INT DEFAULT NULL, -- // parent.id 칼럼 참조
    fd VARCHAR(100) DEFAULT NULL,
    PRIMARY KEY (id),
    KEY ix_parentid (pid),
    CONSTRAINT child_ibfk_1 FOREIGN KEY (pid) REFERENCES tb_parent (id) ON DELETE CASCADE
) ENGINE=INNODB;

INSERT INTO tb_parent VALUES (1, 'parent-1'), (2, 'parent-2');
INSERT INTO tb_child VALUES (100, 1, 'child-100'); 
```

테이블을 생성하고 DataGrip을 이용해 두 개의 커넥션을 생성한 후 작업번호의 순서에 맞게 쿼리를 실행하겠습니다.
다음과 같은 에러가 발생하네요.
**Cannot add or update a child row: a foreign key constraint fails (`rms`.`tb_child`, CONSTRAINT `child_ibfk_1` FOREIGN KEY (`pid`) REFERENCES `tb_parent` (`id`) ON DELETE CASCADE)**

위 에러는 tb_child의 row의 pid를 2로 변경하려했지만 tb_parent에 id가 2인 row가 없기 때문에 발생했습니다.
즉 예상하신대로 해당하는 레코드가 없다는 예외를 반환하고 종료되네요!
테이블 레코드 변경 결과는 아래와 같습니다.

![image](https://user-images.githubusercontent.com/39546083/102749256-0f496600-43a7-11eb-8967-7fa4e40c2f8b.png)
![image](https://user-images.githubusercontent.com/39546083/102749272-14a6b080-43a7-11eb-8e47-b073f67b01f6.png)
