### ISSUE TITLE
[6-2장] Nested Query의 예제

### ISSUE THREAD

**Issue by lxxjn0** [gazi-gazi/real-mysql#4]
> `p.273` 참고. 서브 쿼리는 사용되는 위치에 따라 각각 다른 이름을 지니고 있다.
> - 중첩된 쿼리(Nested Query)
> 	SELECT 되는 칼럼에 사용된 서브 쿼리를 네스티드 쿼리라고 한다.

질문 : Nested Query의 예제를 볼 수 있으면 좋겠어요 :)

**Comment by yebink** [comment]
```sql
EXPLAIN
SELECT e.first_name,
(SELECT COUNT(*) FROM dept_emp de, dept_manager dm WHERE dm.dept_no=de.dept_no AND de.emp_no=e.emp_no) AS cnt
FROM employees e
WHERE e.emp_no=10001;
```

이렇게 SELECT문 안에 사용된 SELECT문을 nested query라고 합니다 🙂
