### ISSUE TITLE
[7.3.1장] 문자 칼럼을 숫자와 비교할 때

### ISSUE THREAD

**Issue by lxxjn0** [gazi-gazi/real-mysql#41]
> `p.384` 이때, MySQL은 문자열 칼럼을 숫자로 변환해서 비교한다...

질문 : 

1. 문자열 칼럼을 숫자와 비교할 경우 인덱스를 타지 않는 것
2. 만약 문자열 칼럼의 레코드 중 숫자로 변경 불가능한 레코드가 있을 경우 쿼리가 실패하는 것

이 두 경우에 대한 실행 화면을 보여주면 좋을 것 같아요~~ :)

**Comment by giantim** [comment]
## 질문 1
먼저 다음과 같이 테이블을 하나 만들께요.
```mysql
create table string_table (
    id INT NOT NULL AUTO_INCREMENT,
    line VARCHAR(30) NOT NULL,
    PRIMARY KEY (id)
)ENGINE=INNODB;
```

그 다음에 line 칼럼을 보조 인덱스로 등록해주겠습니다.
```mysql
ALTER TABLE string_table ADD INDEX idx_line (line);
```
![image](https://user-images.githubusercontent.com/39546083/103473193-26417c80-4dd9-11eb-80eb-d05366cfc73d.png)


문자열 칼럼을 숫자와 비교하는 실행 계획을 확인해보겠습니다.
```sql
EXPLAIN
SELECT * FROM string_table
WHERE line = 10001;
```
![image](https://user-images.githubusercontent.com/39546083/103473198-483aff00-4dd9-11eb-8cb4-eafad02d9e7e.png)

~정상적으로 인덱스를 사용하고 있네요? 🤔~
위 그림에서 type 칼럼 값을 보면 ```index```로 표기되어 있습니다. 이것은 인덱스 풀 스캔을 사용해서 데이터를 찾았다는 뜻이므로 필요한 부분만을 읽는 효율적인 방법이 아닙니다. 특히 지금 테이블은 InnoDB 엔진을 이용하고 있습니다. 모든 보조 인덱스를 풀 스캔하고 데이터를 찾게 되므로 비효율적인 방법이라고 할 수 있습니다.

그럼 이번에는 인덱스를 ```FULLTEXT INDEX```로 생성해 보겠습니다.
기존에 만들었던 B-Tree 인덱스를 지운 후 FULLTEXT 인덱스를 새로 만들겠습니다.
```mysql
ALTER TABLE string_table
DROP INDEX idx_line;

ALTER TABLE string_table
ADD FULLTEXT ftx_line (line);
```
![image](https://user-images.githubusercontent.com/39546083/103473252-fb0b5d00-4dd9-11eb-94c5-73c3464443aa.png)

그리고 동일한 실행계획을 확인해 보겠습니다.
```sql
EXPLAIN
SELECT * FROM string_table
WHERE line = 10001;
```
![image](https://user-images.githubusercontent.com/39546083/103473270-2a21ce80-4dda-11eb-9c7f-f6cfeaa6d5cb.png)

인덱스를 사용하지 못하네요!

~결론은 문자열 칼럼의 인덱스를 전문 검색 인덱스로 만들었을 때 인덱스를 사용하지 못한다 입니다 :)~
결론은 문자열 칼럼과 숫자를 비교할 때는 모두 인덱스를 사용하지 못한다 입니다 :)

## 질문 2
질문 1 에서 사용한 테이블을 그대로 사용하겠습니다. 현재 인덱스 상태는 아래와 같이 프라이머리 키(클러스터링 키)와 전문 검색 인덱스를 갖고 있는 상태입니다.
![image](https://user-images.githubusercontent.com/39546083/103473321-98ff2780-4dda-11eb-9f4b-026f2f4e8694.png)

데이터를 넣어보겠습니다.
```mysql
INSERT INTO string_table (line)
VALUES ('10001'), ('10002'), ('10003'), ('abcdef'), ('10004'), ('10005');
```
![image](https://user-images.githubusercontent.com/39546083/103473353-eda2a280-4dda-11eb-9723-65fb8a3c794f.png)

숫자로 변환 가능한 값들 사이에 ```'abcdef'```라는 숫자로 변환 불가능한 값을 넣어줬습니다.
'abcdef'는 다음과 같이 숫자로 변환 불가능한 값입니다.
![image](https://user-images.githubusercontent.com/39546083/103473398-568a1a80-4ddb-11eb-9d4b-fde311280a48.png)

아래와 같이 숫자를 이용한범위 조건 검색을 해보겠습니다.
```mysql
SELECT * FROM string_table
WHERE line BETWEEN 10001 AND 10005;
```
![image](https://user-images.githubusercontent.com/39546083/103473526-ec727500-4ddc-11eb-9838-d266f6d555d3.png)

검색이 잘 되네요 🤔 하지만 경고 메시지를 하나 포함하고 있군요. 어떤 경고인지 확인해 보겠습니다.
```mysql
SHOW WARNINGS;
```
![image](https://user-images.githubusercontent.com/39546083/103473533-07dd8000-4ddd-11eb-8b35-9afcacb2a3a6.png)
테이블에 저장된 'abcdef' 라는 문자열을 숫자로 바꿀 수 없다는 경고가 포함되어 있네요. 하지만 검색 쿼리의 경우 레벨이 경고이기 때문에 쿼리는 정상적으로 실행됩니다.

그럼 어떤 경우에 조건 비교가 실패해서 쿼리가 실행되지 않을까요? 바로 테이블에게 질의(query)가 아닌 명령(command)을 할 때 입니다.
다음과 같은 쿼리를 실행해 보겠습니다.
```mysql
UPDATE string_table
SET line = '1' WHERE line > 10000;

DELETE FROM string_table
WHERE line > 10000;
```
위 쿼리들은 WHERE 절에 정의한 값 보다 큰 값들에 대한 데이터 변경 / 삭제를 시도합니다. 하지만 쿼리를 실행하면 에러가 발생하고 쿼리 자체가 실행되지 않습니다.
![image](https://user-images.githubusercontent.com/39546083/103473698-cd74e280-4dde-11eb-9406-fe8c722114f7.png)


질의에서는 경고로 처리했지만 명령에서는 에러 레벨이네요 :)
