### ISSUE TITLE
[7.3.3장] UNIX_TIMESTAMP 함수의 시간 기준

### ISSUE THREAD

**Issue by lxxjn0** [gazi-gazi/real-mysql#42]
> `p.402` UNIX_TIMESTAMP() 함수는 1970-01-01 00:00:00로부터 경과된 초의 수를 반환하는 함수다.

질문 : 중요한 질문은 아닌데 왜 1970년 1월 1일이 timestamp의 기준인지 너무 너무 궁금해요~~

**Comment by giantim** [comment]
1970년 1월 1일 00:00:00 부터 지금 까지의 시간을 [유닉스 시간](https://ko.wikipedia.org/wiki/%EC%9C%A0%EB%8B%89%EC%8A%A4_%EC%8B%9C%EA%B0%84)이라고 한다네요! 이것은 [협정 세계시](https://ko.wikipedia.org/wiki/%ED%98%91%EC%A0%95_%EC%84%B8%EA%B3%84%EC%8B%9C)를 유닉스계열에서 표현하는 것이라고 합니다.

1970년이 기준이 된 이유는 단순하게 [이 글의 첫번째 답변을](https://www.quora.com/Why-does-epoch-time-start-with-January-1-1970) 확인하시면 될 것 같네요! 요약하자면 원래 매뉴얼상에 1971년 1월 1일 00:00:00 이 기준 시간이었는데 계산의 편의성을 위해서 1년을 내려 1970년 1월 1일 00:00:00 으로 기준 시간을 정했다고 하네요 :)
