### ISSUE TITLE
[7.4.3장] NULL 비교를 할 때 인덱스를 타지 못하는 경우

### ISSUE THREAD

**Issue by lxxjn0** [gazi-gazi/real-mysql#43]
> `p.434` 하지만 세 번째와 네 번째 쿼리는 인덱스나 테이블을 풀 스캔하는 형태로 처리된다. ... 이러한 비교는 인덱스를 사용하지 못한다는 점을 확실히 알아두기 바란다

질문 : 여기서 세 번째와 네 번째 쿼리가 인덱스를 사용하지 못하는 게 앞에서 나온 것 처럼 비교할 칼럼의 값을 변경해서 인덱스를 사용하지 못하는 거 맞나요??

**Comment by pci2676** [comment]
네 맞아요 결국 WHERE 절에 쓰이는 조건은 `ISNULL()` 함수를 통해 변형된 값이라서 인덱스를 활용하지 못한다고 봐야할 것 같습니다.
