### ISSUE TITLE
[7.4.6장] 뮤텍스 테이블을 사용한 FULL OUTER JOIN

### ISSUE THREAD

**Issue by lxxjn0** [gazi-gazi/real-mysql#44]
> `p.453` 페이지 맨 위의 예시 쿼리
> ```mysql
> SELECT IFNULL(e.yearmonth, n.yearmonth) AS yearmonth, e.event_name, n.news_title
> FROM mutex m
>     LEFT JOIN tab_event e ON m.NO=0
>     LEFT JOIN tab_news n ON m.NO=1 OR n.yearmonth=e.yearmonth
>     LEFT JOIN tab_event e2 ON m.NO=1 AND e2.yearmonth=n.yearmonth
> WHERE n.yearmonth IS NULL OR e2.yearmonth IS NULL;
> ```

질문 : 여러 개의 아우터 조인을 연속해서 하는 부분이 잘 이해가 안돼요.. 😥 어떤 식으로 해당 쿼리가 진행되는지 같이 이야기 나눠보면 좋을 것 같아요!!

**Comment by pci2676** [comment]
mutex
|no|
|---|
|0|
|1|

event1

|year|
|---|
|201102|
|201103|

mutex - event1
|no|year|
|---|---|
|0|**201102**|
|0|**201103**|
|1|**null**|

news

|year|
|---|
|201103|
|201104|

mutex - event1 - news

|no|e1.year|n.year|
|---|---|---|
|0|201102|**null**|
|0|201103|**201103**|
|1|null|**201103**|
|1|null|**201104**|

event2

|year|
|---|
|201102|
|201103|

mutex - event1 - news - event2

|no|e1.year|n.year|e2.year|
|---|---|---|---|
|0|201102|null|**null**|
|0|201103|201103|**null**|
|1|null|201103|**201103**|
|1|null|201104|**null**|

---
결과
|result|no|e1.year|n.year|e2.year|
|---|---|---|---|---|
|⭕️|0|201102|**null**|**null**|
|⭕️|0|201103|201103|**null**|
|❌|1|null|201103|201103|
|⭕️|1|null|201104|**null**|
