### ISSUE TITLE
[7.4.6장] 지연된 조인의 예제 쿼리에 대한 설명

### ISSUE THREAD

**Issue by lxxjn0** [gazi-gazi/real-mysql#45]
> `p.455` 예시로 던져준 쿼리에 대한 실행 계획
> ```mysql
> SELECT e.*
> FROM salaries s, employees e
> WHERE e.emp_no=s.emp_no
>       AND s.emp_no BETWEEN 10001 AND 13000
> GROUP BY s.emp_no
> ORDER BY SUM(s.salary) DESC
> LIMIT 10;
> ```

질문 : 위 쿼리에 대한 실행 계획에서 조인할 때 salaries 테이블의 4개의 row만 읽는 부분이 이해가 잘 안가요..ㅜㅜ

**Comment by pci2676** [comment]
통계자료에 기반한 row라서 정확하다고 볼수 없지만 참고하여 이정도 양의 루프가 실행되겠구나 하고 추측할 수 있는 자료입니다.
