### ISSUE TITLE
[7-4-8장] 복수 개의 컬럼을 각각 다른 방향으로 ORDER BY할 경우 인덱스 활용은 최신 MySQL 버전에서도 지원하지 않는가

### ISSUE THREAD

**Issue by toneyparky** [gazi-gazi/real-mysql#46]
> `p.470`  여러 칼럼을 조합해서 정렬시, 칼럼의 정렬 순서가 혼용되면 인덱스를 이용할 수 없다. 만약 ASC와 DESC가 혼용된 정렬이 인덱스를 사용하게 하려면 칼럼의 값 자체를 변형시켜 테이블에 저장하는 것이 유일한 해결책이다.

질문 :
책은 5.x 초반 버전을 사용하고 있고 당시에는 책의 설명대로 정렬 방향이 혼용되었을 경우에 인덱스를 사용할 수 없는데요. 
이후의 버전에서는 이 부분이 개선되었는지 궁금합니다.

**Comment by toneyparky** [comment]
[MySQL 8.0 문서](https://dev.mysql.com/doc/refman/8.0/en/order-by-optimization.html)를 참고해보면 질문해주신 부분에 대해서 `Optimizer`가 최적화를 시켜서 인덱스를 활용할 수 있도록 처리한다는 부분을 확인할 수 있습니다. 


>Two columns in an ORDER BY can sort in the same direction (both ASC, or both DESC) or in opposite directions (one ASC, one DESC). A condition for index use is that the index must have the same homogeneity, but need not have the same actual direction.
If a query mixes ASC and DESC, the optimizer can use an index on the columns if the index also uses corresponding mixed ascending and descending columns:
~~~SQL
SELECT * FROM t1
  ORDER BY key_part1 DESC, key_part2 ASC;
~~~
> The optimizer can use an index on (key_part1, key_part2) if key_part1 is descending and key_part2 is ascending. It can also use an index on those columns (with a backward scan) if key_part1 is ascending and key_part2 is descending. See Section 8.3.13, “Descending Indexes”.

다만 문장을 해석해보면 `Optimizer`는 제한된 최적화만 수행할 수 있습니다. 


위의 경우에서 `key_part1`은 내림차순 `key_part2`는 오름차순으로 정렬하려 합니다. 
이 경우에 미리 인덱스(key_part1, key_part2)가 각각 (내림차순, 오름차순) 혹은 (오름차순, 내림차순) 쌍으로 정렬되어 세팅되어 있는 경우에 대해서만 최적화가 적용됩니다. 
즉 인덱스가 (내림, 내림)이나 (오름, 오름)으로 정렬되어서 저장되어 있을 경우에는 위에 있는 쿼리를 처리할 때 인덱스를 활용하지 못하는 책과 같은 상황이 발생하는 것입니다.

[추가 정보] 인덱스를 기본값이아닌 내림차순으로 정렬하는 기능은 [MySQL 8.0 버전](https://tech.kakao.com/2018/06/19/mysql-ascending-index-vs-descending-index/)에서 새롭게 추가 되었습니다.

---

**정리하자면** 
1. `MySQL 8.0`버전에는 인덱스 자체를 내림차순으로 저장할 수 있는 기능이 추가되었습니다.
2. 이 기능을 활용하여 정렬하려는 컬럼들의 방향에 맞는 인덱스를 미리 설정해둔다면 인덱스를 활용할 수 있습니다.

**Comment by jjj0611** [comment]
인덱스를 역순으로 저장하는 것이 생겼고(원래는 음수화 하여 저장한다든가 해야했는데),
저장된 인덱스의 순서를 전체의 방향성이 맞아진다면 인덱스를 활용할 수 있는 점(한 개라도 방향이 틀어지면 인덱스를 사용할 수 없는 점)은 동일하다고 보면 되겠네요!
