### ISSUE TITLE
[7-4-8장] 최신 MySQL에서는 함수를 이용한 인덱스(Function based index)를 지원하는가

### ISSUE THREAD

**Issue by toneyparky** [gazi-gazi/real-mysql#47]
> `p.474` 미리 표현식의 연산 결과를 위한 별도의 칼럼을 추가해서 레코드가 추가되거나 갱신될 때에 해당 칼럼을 계속 업데이트하는 방식이 최선이다. **MySQL은 함수를 이용한 인덱스가 없기에 표현식의 결과를 저장하는 별도의 칼럼을 생성해야 한다.** 그리고 그 칼럼에 인덱스를 생성하고 표현식의 정렬이 필요할 때는 이미 연산 결과값이 저장된 칼럼으로 ORDER BY를 사용하는 것이다. 

질문 : 책은 MySQL 버전 5.x대를 다루고 있습니다. 유용한 기능으로 보이는데 저 버전에는 지원하지 않네요. 최신 버전에서는 함수를 이용한 인덱스를 지원하는지 궁금합니다.

**Comment by giantim** [comment]
#36 이 내용이랑 같은 질문 아닌가요?

**Comment by toneyparky** [comment]
오 이미 다뤘던 내용이네요.
고맙습니다
이슈는 바로 닫을게요~
