### ISSUE TITLE
[7-4-9 장] MySQL 5.7에서 WHERE 절의 서브 쿼리의 최적화 변경

### ISSUE THREAD

**Issue by giantim** [gazi-gazi/real-mysql#49]
책에서 소개한 아래 두 가지 쿼리는 MySQL 구버전에서 실행한 쿼리여서 제대로 최적화가 안되었습니다. 우리가 스터디에서 사용하는 MySQL 5.7에서 쿼리의 실행 계획을 살펴보면 책에서 설명한 것과 다르게 최적화가 되어서 나타납니다. 바뀐 결과에 대해서 다같이 분석해보면 좋을것 같아요 :)

> `p.479` WHERE 절에 단순 비교를 위해 사용된 서브 쿼리

```mysql
EXPLAIN
SELECT * FROM dept_emp de
WHERE de.emp_no=
  (SELECT e.emp_no
   FROM employees e
   WHERE e.first_name='Georgi' AND e.last_name='Facello' LIMIT 1);
```

> `p.480` WHERE 절에 IN과 함께 사용된 서브 쿼리 - IN (subquery)

```mysql
EXPLAIN
SELECT * FROM dept_emp de
WHERE de.dept_no IN
  (SELECT d.dept_no FROM departments d WHERE d.dept_name='Finance');
```

**Comment by toneyparky** [comment]
첫 번째 쿼리에 대한 5.1 버전의 실행계획입니다.
![image](https://user-images.githubusercontent.com/37579660/104791385-d5b91e80-57dd-11eb-9975-085e71560c68.png)

5.7 버전의 실행계획입니다.
![image](https://user-images.githubusercontent.com/37579660/104791409-e8cbee80-57dd-11eb-8df5-977b9ad85281.png)




두 번째 쿼리에 대한 5.1 버전의 실행계획입니다.
![image](https://user-images.githubusercontent.com/37579660/104791452-1749c980-57de-11eb-8988-c39210284dd7.png)

5.7 버전의 실행계획입니다.
![image](https://user-images.githubusercontent.com/37579660/104791464-229cf500-57de-11eb-8787-90c610c3f224.png)


5.7 버전에서는 말씀해주신대로 두 쿼리 모두 ref로 진행되는 것을 확인할 수 있네요. 
바뀐 결과에 대해서 다 같이 분석해보죠~
