### ISSUE TITLE
[7-5장] LAST_INSERT_ID() 함수의 성능 개선

### ISSUE THREAD

**Issue by giantim** [gazi-gazi/real-mysql#50]
질문은 아니고 책의 내용이랑 달라진 부분이 있어서 공유해요!

> `p.500` 또한, AUTO_INCREMENT 칼럼이 포함된 테이블에 INSERT 할 때 0이나 NULL이 아닌 정수 값을 강제로 저장하면 LAST_INSERT_ID() 함수로 그 값을 가져올 수 없다.

책에 나온 내용은 MySQL 5.7 버전에서는 개선이 되었네요 :)
다음과 같은 쿼리를 실행했을 때 동일하게 가장 최근에 AUTO_INCREMENT가 자동으로 증가시켜준 칼럼 값이 반환되게 됩니다.

```mysql
create table tb_autoincrement (
    id INT NOT NULL AUTO_INCREMENT,
    name varchar(30),
    PRIMARY KEY (id)
)ENGINE=INNODB;

INSERT INTO tb_autoincrement VALUES (NULL, 'Lee');
SELECT LAST_INSERT_ID();

INSERT INTO tb_autoincrement VALUES (6, 'Kim');
SELECT LAST_INSERT_ID();
```

두 번째 INSERT 쿼리에서 6이라는 id 값을 강제로 넣었으므로 책의 내용 대로라면 LAST_INSERT_ID() 값이 0을 반환해야 하지만 1을 반환하는 것을 알 수 있습니다 :)
![image](https://user-images.githubusercontent.com/39546083/106219192-3e5fbc80-621c-11eb-908b-aea702965b80.png)

**Comment by lxxjn0** [comment]
자이언트씨 감사합니다 :)

아 추가적으로 `insert` 쿼리에서 하나의 레코드만 추가하는 경우는 `last_insert_id()` 함수의 결과가 기대하는 값을 반환합니다.

> 만약 하나의 레코드가 추가되었는데 해당 레코드의 `auto_increment` 값이 2라면 `last_insert_id()` 함수의 값도 2가 반환됩니다.

그러나 `insert` 쿼리에서 여러 레코드를 추가하는 경우 `last_insert_id()` 함수의 결과가 (제가) 기대하는 값을 반환하지는 않았습니다.

> 만약 4개의 레코드가 추가되었고 각각의 레코드의 `auto_increment` 값이 3, 4, 5, 6 이라면 `last_insert_id()` 함수의 값은 3을 반환합니다.

저는 당연히 마지막 값인 6을 반환한다고 생각했는데 `insert` 쿼리가 실행하는 순간에서의 가장 최신의 `auto_increment` 값이 반환되는 것 같습니다.
