### ISSUE TITLE
[7-5-1장] AUTO_INCREMENT 값 가져오기

### ISSUE THREAD

**Issue by yebink** [gazi-gazi/real-mysql#51]
> `p.499` 책 내용
AUTO_INCREMENT 값을 조회할 때 `SELECT MAX(id) FROM ...` 이렇게 최댓값을 가져오는 방식은 현재 커넥션뿐 아니라 다른 커넥션에서 증가된 AUTO_INCREMENT 값까지 가져올 수 있으므로 사용하지 않는 것이 좋다.

질문 :
이 방식이 왜 나쁜지 이해가 안 갑니다. 오히려 다른 커넥션에서 증가시킨 가장 최신의 AUTO_INCREMENT 값이라면 저렇게 가져오는 것이 도 효율적이지 않나요?

**Comment by lxxjn0** [comment]
저도 그렇게 생각하긴 했습니다.. (관련된 내용이 이해가 안가서 찾아봐도 왜 좋지 않은지에 대한 글이 없더군요..)

그런데 한 번 직접 실행해봤습니다.

```
a 커넥션에서 `insert` 쿼리를 실행하고 `last_insert_id()` 함수를 실행하니깐 1이 나왔습니다.
그리고 b 커넥션에서 똑같은 테이블에 다시 `insert` 쿼리를 실행하고 `last_insert_id()` 함수를 실행하니깐 2가 나왔습니다.

돌아와서 a 커넥션에서 `last_insert_id()` 함수를 실행하니 전과 동일하게 여전히 1이 나왔습니다.
그리고 a 커넥션에서 `insert` 쿼리를 실행하고 `last_insert_id()` 함수를 실행하니깐 3이 나왔습니다.
```

사실 테이블의 입장에서의 `auto_increment` 값을 생각하면 `select max(member_id) from ...`의 값이 올바른 값을 반환하는 것은 맞다고 생각합니다.

그런데 책에서 의도하는(이야기하는?) `auto_increment`의 값이란 테이블의 `auto_increment` 값이 아닌 커넥션에서의 마지막 `auto_increment` 값을 말하는 것 같습니다. 이런 가정에서는 `select max(member_id) from ...` 쿼리가 원하는 값을 반환하지 않기 때문이죠.

저는 책에서 말하는 가장 최신의 `auto_increment` 값이 커넥션에서의 가장 최신이라는 의미라고 생각하니까 질문하신 부분이 이해가 가긴 했는데 만약 테이블에서의 최신의 `auto_increment` 값이라고 하면 ... 저도 잘 이해가 가진 않습니다 ㅠㅠ

**Comment by jnsorn** [comment]
관리 측면에서 AUTO-INCREMENT 값은 테이블별로(즉, 여러 커넥션에서 증가된 값인 최종 값으로) 관리되는 게 맞지만 책에서는 로직이나 쿼리 작성 시 max를 지양하라는 의미로 받아들여집니다.

예를 들어, 하나의 커넥션이 시작되고 그 내에서 가장 마지막 레코드의 아이디를 가져와 그 값으로 다른 작업을 수행하는데 만약 max를 이용해 가져오게 된다면 그 사이에 수행된 다른 insert문에 의해 영향을 받을 수 있을 거 같아요. 

그래서 로직이나 쿼리 작성 시 하나의 커넥션 안에서 안전하게 수행하기 위해 last_insert_id()를 사용하라고 하지 않았을까 생각합니다.
