### ISSUE TITLE
[7-5-2장] INSERT IGNORE

### ISSUE THREAD

**Issue by yebink** [gazi-gazi/real-mysql#52]
> `p.501` `INSERT IGNORE`는  PK나 UK로 인한 중복 에러가 발생해도 해당 레코드는 무시하고 작업을 계속 진행할 수 있게 해준다고 설명이 되어 있습니다. 예시로 로그성 테이블을 들고 있어요.

질문 :
그런데 바로 아래에 PK나 UK 중복이 발생할 때 값이 저장되지 않는 경우라고 설명되어 있는데, 그럼 바로 위에서 예시로 든 로그성 테이블에서 사용해도 남겨야 할 로그가 저장되지 않는 것 아닌가요?

**Comment by jnsorn** [comment]
넵 맞습니다. 저장 안 돼요.

`해당 레코드는 무시하고 작업을 계속 진행한다`와 `저장되지 않는다`를 같은 맥락으로 보고 이해하면 될 거 같아요.

남겨야 할 로그는 이미 존재하고, 이로 인해 중복 에러가 발생한 것이기 때문에 해당 INSERT문은 저장되지 않고 지나가도 문제가 없는거죠!

**Comment by yebink** [comment]
아 이미 저장된 로그에 대해서 무시된다는 뜻이었군요!
제가 잘못 이해했던 것 같네요 감사합니다~

**Comment by jnsorn** [comment]
저장된 로그에 대해 무시한다기 보다는 저장될 로그에 대해 무시한다는 표현이 더 맞는 것 같아요.
이미 동일한 로그가 저장되어 있으니 중복되는 레코드는 무시되는(저장되지 않는) 옵션 같아요!
