### ISSUE TITLE
[7-9-5장] FOUND_ROWS()가 항상 1을 반환하는 문제

### ISSUE THREAD

**Issue by giantim** [gazi-gazi/real-mysql#53]
> `p.555` 

7.9.5 SQL_CALC_FOUND_ROWES 단원의 예제에서 SQL_CALC_FOUND_ROWS가 포함된 쿼리를 실행하고 FOUND_ROWS() 함수를 실행하면 먼저 실행한 쿼리의 총 결과 개수를 보여준다고 했습니다. 하지만 DataGrip에서 실행하면은 항상 FOUND_ROWS() 함수를 실행한 결과값이 1이 나옵니다.

이 문제에 대해서는 [여기](https://stackoverflow.com/questions/14847467/select-found-rows-return-1-in-mysql)의 두 번째 답변을 참고해주세요! IDE를 이용해 쿼리를 실행하면은 IDE가 쿼리 실행 이후에 추가적인 쿼리를 실행하기 때문에 FOUND_ROWS() 함수의 결과값이 1 또는 0 또는 에러가 발생할 수 있다고 합니다.

도커에 들어가서 MySQL 서버에서 직접 예제 쿼리를 실행하면 아래와 같이 결과가 정상적으로 나옴을 확인할 수 있습니다 :)
![image](https://user-images.githubusercontent.com/39546083/107901525-3a0b0180-6f87-11eb-9eab-35a138dc13ee.png)

**Comment by jnsorn** [comment]
역시 라빈 최고예요. 이슈 보고 IDE가 추가적으로 어떤 쿼리를 실행하는 건지 궁금해서 저도 테스트 해봤는데 참고할 사람은 참고하세요! 
<img width="821" alt="스크린샷 2021-02-22 오전 11 44 04" src="https://user-images.githubusercontent.com/31095063/108650712-8ca66980-7503-11eb-8d49-22efdc966a10.png">
<img width="350" alt="스크린샷 2021-02-22 오전 11 45 03" src="https://user-images.githubusercontent.com/31095063/108650717-8f08c380-7503-11eb-89e0-0dacdf251aed.png">

**Comment by giantim** [comment]
질문이 추가로 들어왔는데요!
``IDE가 아닌 MySQL 서버에서 직접 쿼리를 실행했을 때는 어떤 쿼리가 추가적으로 실행되는가`` 입니다.

쿼리를 실행한 서버는 저희 스터디 도커 서버이고 쿼리문은 아래와 같습니다.
```mysql
show variables like 'profiling';
set profiling = 1; -- 이 두 쿼리는 프로파일링 기능이 처음에 꺼져있어서 실행합니다.

select sql_calc_found_rows * from employees where first_name = 'Georgi' limit 0, 20;
select found_rows();
show profiles;
```

결과는 아래와 같습니다.
![image](https://user-images.githubusercontent.com/39546083/108704802-db79f080-754f-11eb-9c3d-0e24f6078471.png)
IDE와 달리 조회 쿼리 이외에는 아무런 추가적인 쿼리가 실행되지 않습니다.

하지만 경고를 하나 포함하고 있네요. 어떤 경고인지 알아보겠습니다.
![image](https://user-images.githubusercontent.com/39546083/108705324-7ffc3280-7550-11eb-880a-041124af09e2.png)
``SHOW PROFILES`` 구문이 곧 deprecated 된다는 경고문입니다.
추후 MySQL 버전에서는 [문서](https://dev.mysql.com/doc/refman/5.6/en/performance-schema-query-profiling.html)를 참고해서 프로파일 기능을 사용하시면 됩니다 :)
