### ISSUE TITLE
[6-2장] 인덱스 레인지 스캔

### ISSUE THREAD

**Issue by begaonnuri** [gazi-gazi/real-mysql#6]
> `p.289` '주의'로 박싱된 부분

질문 : const, ref, range 이렇게 3가지가 묶여서 중요하게 사용 되는것 같은데(index 접근 방법의 사용 조건이 된다던지 묶여서 인덱스 레인지 스캔으로 언급된다던지) 3개만 따로 표같은걸로 명확하게 비교해주면 좋을것같아

**Comment by yebink** [comment]
`p.291` 맨 첫 번째 줄 보면 range, const, ref는 WHERE 조건이 있어야만 사용할 수 있는 것처럼 보여.
그리고 그 이후에 PK나 UK 등등 제약조건에 따라 어떤 것일지 결정되는 것 같아.

그래도 표가 필요하신가 자네?

**Comment by begaonnuri** [comment]
## 인덱스 레인지 스캔(const, ref, range)

### 공통점

PK나 Unique키 칼럼을 WHERE절로 검색한 경우

### 차이점

#### 1. const

오직 1건만을 반환하는 경우.
PK가 복합키(A, B)로 이루어져있고 WHERE절에서 A, B 둘 중 하나만 사용한 경우엔 ref로 표시됨.

#### 2. ref

PK나 Unique키 칼럼을 WHERE절로 검색한 경우 중 const, range가 아닌 모든 경우

#### 3. range

 `<`, `>`, `IS NULL`, `BETWEEN`, `IN`, `LIKE`등의 연산자를 이용해 인덱스를 검색하는 경우
