### ISSUE TITLE
[6-2장] index 접근 방법

### ISSUE THREAD

**Issue by begaonnuri** [gazi-gazi/real-mysql#7]
> `p.291` 이 예제의 실행 계획은 테이블의 인덱스를 처음부터 끝까지 읽는 index 접근 방식이지만 LIMIT 조건이 있기 때문에 상당히 효율적인 쿼리다. 단순히 인덱스를 거꾸로 (역순으로) 읽어서 10개만 가져오면 되기 때문이다. 하지만 LIMIT 조건이 없거나 가져와야 할 레코드 건수가 많아지면 상당히 느려질 것이다.

질문 : 

LIMIT의 경우 MySQL에서 제일 마지막에 실행되는 걸로 알고 있는데, (join->where->having->select->order by->limit 순서)
그렇다면 스캔을 모두 한 후 LIMIT에 명시한 숫자 만큼 잘라서 가져오기 때문에 효율과 상관이 없을것같은데 여기서 말하는 효율이 뭘 말하는걸까?

**Comment by pci2676** [comment]
SELECT 의 결과를 LIMIT 갯수만큼 가져오면 쿼리 실행이 끝나기 때문에 실행시간의 차이가 발생할 수 있어
예시로 확인해보자!

일단 salaries 테이블에는 280만개의 데이터가 있어
<img src="https://user-images.githubusercontent.com/13347548/99946391-a2e44280-2db9-11eb-9352-c087afc88c3f.png" width=400/>

아래의 쿼리를 먼저 실행하고 실행 시간을 확인해볼게
```sql
SELECT COUNT(*)
FROM salaries
ORDER BY from_date DESC
```
![image](https://user-images.githubusercontent.com/13347548/99947027-b17f2980-2dba-11eb-940e-98d55a5d2b78.png)
2.3초 정도 소요되는 걸 확인할 수 있어

이번엔 LIMIT을 포함해서 쿼리를 날려볼게
```sql
SELECT COUNT(*)
FROM salaries
ORDER BY from_date DESC
LIMIT 10
```
![image](https://user-images.githubusercontent.com/13347548/99947145-dd9aaa80-2dba-11eb-901d-d0435bc79548.png)
0.6초로 속도가 굉장히 차이가 많이 나는 것을 확인 할 수 있어!

**Comment by jjj0611** [comment]
이 경우에는 salaries에서 가져오는거니까 index 스캔을 할거라는 실행 계획을 세우고,
그 중에서 역순으로 불러올 거 + 10개까지 가져온다는 것을 아니까
역순으로 읽으면서 10개만 끝났을 때 끝내면 되니까 LIMIT에 걸린만큼 데이터를 가져와서 속도가 빨라질 수 있는거지!

```sql
SELECT * FROM departments ORDER BY dept_name DESC LIMIT 10;
```

이라고 했을 때 dept_name이 index가 걸려 있어서 스캔 시에 dept_name의 index를 역순으로 읽어주면 되는거지!

근데 여기서도 dept_name에 index가 걸려 있어서 이 LIMIT이 의미가 있는거야

@pci2676 찬인이가 올려준 저 SQL 문에서도
```sql
SELECT COUNT(*)
FROM salaries
ORDER BY from_date DESC
LIMIT 10 
```

이게 LIMIT이 걸려 있는게 의미 있는 이유는 from_date에 index가 걸려서 그래

```sql
SELECT COUNT(*)
FROM salaries
ORDER BY to_date DESC
LIMIT 10 
```

이 SQL 문에서 to_date에는 index가 안걸려 있어서 index 스캔을 못하고 ALL type의 스캔을 하다보니까
LIMIT이 있든지 없든지 무조건 ORDER BY를 실행하고 그 중에서 10개를 잘라오기 때문에
LIMIT의 존재 유무와 수에 상관 없이 무조건 FULL SCAN이 일어나!


**정리**
LIMIT을 걸어도 결국 ORDER BY 한 결과를 기준으로 LIMIT을 건다.
그렇기 때문에 INDEX FULL SCAN이 아닌 경우 전체 결과 값을 ORDER BY 하게 된다.
INDEX로 스캔을 할 수 있는 경우 INDEX만 타고 LIMIT 값만큼 읽어오면 되기 때문에 더 효율적이다!

from_date에 index가 걸려 있지 않다고 생각해서 헷갈릴까봐 추가했음!
