### ISSUE TITLE
[6-2장] 실행 계획 순서(driving table)을 정하는 기준

### ISSUE THREAD

**Issue by yebink** [gazi-gazi/real-mysql#8]
> `p.298` Distinct 예시

질문 :
![image](https://user-images.githubusercontent.com/19922698/100495565-29b96680-3190-11eb-85cb-0af5be59c804.png)

위 그림에서 from 절의 순서를 바꿨음에도 실행 계획은 동일하게 나오는 것을 확인했어.

`p.267`에 보면 실행 순서는 위에서 아래로 표시되고, 위쪽에 출력된 결과가 먼저 접근한 테이블이라는 말이 있는데

**from 절의 순서**와 **먼저 접근한 테이블 순서**가 무관하다는 점이 이해가 안 가.

**Comment by KimSeongGyu1** [comment]
뇌피셜이긴 한데 
1. 둘의 id가 같으면 동시 접근이라 봐도 무방하다고 생각하구
2. 실행 계획에서 테이블의 순서는 알파벳 순인듯

직접 de와 e 값을 내 맘대로 바꿔서 테스트 해본 결과 알파벳 순으로 순서가 바뀌는 것을 확인

**Comment by giantim** [comment]
> `p.320`

질문 :
```sql
EXPLAIN
SELECT *
FROM dept_emp de, employees e
WHERE de.from_date>'2005-01-01' AND e.emp_no<10904;
```
이 쿼리에서 두 테이블을 조인할 때 employees 테이블을 먼저 읽어서 Using join buffer가 사용되었는데 employees 테이블이 왜 dept_emp 테이블보다 먼저 읽혔는지 궁금합니다.

**Comment by begaonnuri** [comment]
이건 찾아봤는데

MySQL 각 절의 실행순서, 실행 계획에 대한 내용만 나오고 FROM 내부에서 어떤 처리가 일어나는지는 못찾겠네 ㅠㅠ
일단 Stuck 걸어놓을게.

**Comment by giantim** [comment]
> `p.368`

여기에 나와있는 
```sql
SELECT *
FROM dept_emp de, employees e
WHERE de.from_date > '1995-01-01' AND e.emp_no < 109004;
```
의 쿼리의 실행 계획을 확인해보면 dept_emp 테이블이 드라이빙 테이블로 설정되네요!
위에 적은 쿼리와 조건이 비슷해 보이는데 반환하는 결과값에 큰 차이가 있어서 옵티마이저에 의해 더 효율적으로 검색을 수행할 수 있는 테이블을 기준으로 드라이빙 테이블이 설정되는것 같습니다.

**Comment by yebink** [comment]
`p.443~444` 에 보면, **드리븐 테이블에서는 인덱스 탐색 작업과 스캔 작업을 드라이빙 테이블에서 읽은 레코드 건수만큼 반복한다**고 되어 있다. 즉, 드라이빙-드리븐이 1:1로 조인되더라도, 드리븐 테이블을 읽는 것이 훨씬 큰 부하를 차지한다는 것이다.
그래서 **옵티마이저는 항상 드라이빙 테이블이 아닌, 드리븐 테이블을 최적으로 읽을 수 있게 (ex. 인덱스를 탄다거나~) 실행 계획을 수립한다.**
