### ISSUE TITLE
[6-2장] Index range scan vs full scan

### ISSUE THREAD

**Issue by pci2676** [gazi-gazi/real-mysql#9]
> `p.297` 인덱스 레인지 스캔이 아니라 풀 스캔을 선택

질문 : 인덱스 레인지 스캔이 어떻게 동작하길래 많은 레코드를 읽어야하는 상황에서 풀스캔을 선택하는 걸까?

**Comment by yebink** [comment]
인덱스 레인지 스캔은 B-Tree 인덱스에서 `인덱스 루트`부터 `리프 노드`까지 수직 탐색을 하고, 필요한 범위만큼 수평 탐색을 한다고 하네.
이 경우에는 모든 row를 탐색해야 하니까 전체 B-Tree를 조회해야 할거고, 확실한 건 이 방법보다 풀 스캔이 더 빠르니까 풀 스캔으로 진행하겠지?

풀 스캔은 어떤 방식으로 진행되는지도 궁금해!

**Comment by begaonnuri** [comment]
풀 테이블 스캔의 경우 다중 블록단위 I/O를 사용해서 여러개의 블록 단위로 데이터를 읽어와.
Oracle같은 DBMS는 이렇게 가져오는 수를 조절할 수 있다는데, MySQL의 MyISAM에선 불가능해.

하지만 InnoDB에선 다르게 처리하는데,
특정 테이블의 연속된 블록을 읽는 경우 백그라운드 쓰레드에서 리드 어헤드라는 작업을 해.
리드 어헤드는 말 그대로 **미리 읽는 것**이야.
앞으로 필요할 걸 예상해서 미리 디스크에서 InnoDB 버퍼 풀에 가져오는 작업을 말해.

따라서 풀 테이블 스캔을 하면 처음 몇 개의 블록은 포그라운드에서 실행하지만,
어느정도 시점이 되면 백그라운드 스레드가 리드 어헤드로 버퍼에 가져와놓고 포그라운드 스레드는 버퍼에 있는걸 사용하는 식으로 동작한다고 생각하면 돼.

간략하게 이런식이고,
더 자세한건 해당 단원일때 알아봅시다!
책의 330p를 참고해주세요!
